### ISSUE TITLE
urlfrontier.StatusUpdaterBolt fails after reconnecting the URL Frontier to the SC

### ISSUE THREAD

**Issue by michaeldinzinger** [DigitalPebble/storm-crawler#1043]
Hello all,
the following issue popped up during some experimenting with the URL Frontier and a derivate of the SC: When the URL Frontier service is killed and restarted, the serving of new URLs to the StormCrawler via the urlfrontier.Spout continues to work nicely as if the Frontier service would never have been down.
However, the StatusUpdaterBolt seems to fail all tuples that it receives (after the restart, you can see no acks, but only fails for the StatusUpdaterBolt in the Storm UI). It seems that the cancelled connection between the Crawler and the frontier cannot be resumed after the restart of the URL Frontier.
As a consequence, after the Frontier service is restarted, also the SC topology has to be killed and resubmitted, which is not very convenient. Maybe a little code fix in the StatusUpdaterBolt would solve this issue.

**Comment by jnioche** [comment]
Fixed in #1054
