### ISSUE TITLE
nextFetchDate field in SOLR schema should be optional

### ISSUE THREAD

**Issue by syefimov** [DigitalPebble/storm-crawler#1051]
- [ ] Bug report.

Solr "status" collection 

Remove "required" attribute from nextFetchDate field. nextFetchDate is null in case of "ERROR" status inside StatusUpdaterBolt

`<field name="nextFetchDate" type="pdate" stored="true" indexed="true"/>`

**Comment by jnioche** [comment]
Merged, thanks @syefimov
