### ISSUE TITLE
[Maven] publish src as artefacts

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#106]
I don't think we publish the src code in a jar as part of the artefacts, do we?

**Comment by jnioche** [comment]
have assigned the issue to you as you are our maven expert ;-)

**Comment by jakekdodd** [comment]
"expert" :)

I'll get on this

**Comment by jnioche** [comment]
We actually do [http://search.maven.org/#search%7Cga%7C1%7Cstorm%20crawler]
