### ISSUE TITLE
Fix flaky test in AdaptiveSchedulerTest.testSchedule

### ISSUE THREAD

**Issue by rzo1** [DigitalPebble/storm-crawler#1076]
```bash
AdaptiveSchedulerTest.testSchedule:101 expected:<2023-05-22T10:05:20Z> but was:<2023-05-22T10:05:19Z>
```

Seems to be a flaky test. We should investigate.-

**Comment by jnioche** [comment]
A simple case of 2 instants being rounded to 2 different seconds. Could change the tests so that we check that they are within one second of each other instead of being equal
