### ISSUE TITLE
HttpRobotRulesParser.java is not correctly formatted

### ISSUE THREAD

**Issue by michaeldinzinger** [DigitalPebble/storm-crawler#1077]
Hello, after the merge of my latest PR, the validation of the code format fails.
It results a BUILD FAILURE for `mvn clean install` of the latest SC SNAPSHOT version.
```
[ERROR] Failed to execute goal com.cosium.code:git-code-format-maven-plugin:4.2:validate-code-format (validate-code-format) on project storm-crawler-core: /<...>/storm-crawler/core/src/main/java/com/digitalpebble/stormcrawler/protocol/HttpRobotRulesParser.java is not correctly formatted ! -> [Help 1]
```
I tried to hotfix the formatting error asap to not block anyone, but unfortunately even with the automatic code formatting of my IDE using the Google Java style I couldn't get rid of the formatting mistake. I'm very thankful for any help.

**Comment by jnioche** [comment]
`mvn git-code-format:format-code -Dgcf.globPattern=**/*`

Have applied the commit in 91ae9778
