### ISSUE TITLE
No Such method error due to jar conflict withing storm crawler 2.7

### ISSUE THREAD

**Issue by msghasan** [DigitalPebble/storm-crawler#1087]
This issue is appearing when we are running in local mode trying to fetch the selenium driver object.

If I investigate the dependency tree I can see remote driver is using io.netty jars of 4.184.Final and in aysynch-http-client 2.12.3 they are using io.netty 4.1.60.

![Error Screen](https://github.com/DigitalPebble/storm-crawler/assets/32441552/583b6403-1204-4f24-865a-e986e7bd3b1f)

![Dependency tree](https://github.com/DigitalPebble/storm-crawler/assets/32441552/a3ad5a35-15e0-48db-8b15-61e798c5e6e5)

Even if i try to exclude the 4.1.6.0 io.netty jars the prolem is not resolved.

Can you guys provide some information on this so that I can fix this and produce a PR

**Comment by rzo1** [comment]
Looks like a classpath issue. Best way would be to urge the selenium guys to fix up their dependency tree.

**Comment by msghasan** [comment]
Let me raise an issue with selenium

**Comment by msghasan** [comment]
But One more thing I would like to add is, when I create a sample class within the storm crawler project. and run it via main method, the object is getting created and we are able to visit the url. It's only failing while running in storm crawler

**Comment by rzo1** [comment]
The JAR run by Storm is a "shade", ie everything is packed into a single jar. If you have overlapping transient dependencies, it is a problem. There should also be warnings regarding that in the output. Best way to fix would be to resolve the transient dependency issue in selenium, I guess.

**Comment by msghasan** [comment]
shall I update the dependency of selenium to higher version in the pom.

**Comment by rzo1** [comment]
If there were related changes, that would be an option, yes.

**Comment by msghasan** [comment]
Nah

> If there were related changes, that would be an option, yes.

No it did not resolve the problem. I think storm-client2.4.0 also uses io.netty 4.1.84.Final

Don't know how to resolve this problem

**Comment by dhaneshsabane** [comment]
@msghasan - This should solve your problem - https://github.com/DigitalPebble/storm-crawler/discussions/1092#discussioncomment-7017067

Thanks to @rzo1 ❤️
