### ISSUE TITLE
NimbusLeaderNotFoundException when upgrading to the latest version of storm crawler with jdk 17

### ISSUE THREAD

**Issue by batman0007** [DigitalPebble/storm-crawler#1104]
I'm seeing various errors while upgrading the stormcrawler version from 1.15 to 2.9, storm version 2.5.0 and java 8 to 17 simultaneously. 
First there were test failure with this exception:" java.lang.IllegalArgumentException: Unable to canonicalize address localhost/:2000 because it's not resolvable" when stormcarwler was at the lower version
 and on updating the version, the error was: "The following artifacts could not be resolved: org.clojars.bipinprasad:carbonite:jar:1.6.0 (absent)."
 On adding this dependency, now this is the error: "org.apache.storm.utils.NimbusLeaderNotFoundException: Could not find leader nimbus from seed hosts [localhost]. Did you specify a valid list of nimbus hosts for config nimbus.seeds?"
Are there compatibility issues with stormcrawler version 2.9 and jdk 17/11 or am I missing something?(java and maven paths are set and pom has all dependencies) Is anyone else seeing this issue?

**Comment by jnioche** [comment]
Both StormCrawler and Apache Storm are both tested against JDK 11/17. Your issues seem mostly related to configuring Storm and not so much StormCrawler. Maybe best to ask questions about how to set up Storm to the Storm user list, you will get a larger audience.
