### ISSUE TITLE
org.apache.http.NoHttpResponseException: The target server failed to respond

### ISSUE THREAD

**Issue by visakini** [DigitalPebble/storm-crawler#1105]
We are getting this exception intermittently in our application .

Http client version is 4.5.10

Will retry request will avoid this error.

Thanks!

**Comment by jnioche** [comment]
Can you elaborate a bit please? Are you suggesting to add something similar to https://gist.github.com/devrath/e86d591e0e03732f5050bc8a798c60b6 ?

**Comment by visakini** [comment]
We are adding like this
  public boolean retryRequest(IOException e, int retryCount, HttpContext httpCtx) {
                if (retryCount >= 3){
                    Logger.warn(CALLER, "Maximum tries reached, exception would be thrown to outer block");
                    return false;
                }
                if (e instanceof org.apache.http.NoHttpResponseException){
                    Logger.warn(CALLER, "No response from server on "+retryCount+" call");
                    return true;
                }
                return false;
            }
        };
After this the request suceeds but is there any alternative solution for avoiding NoHttpResponseException.This is just a work around

**Comment by jnioche** [comment]
Could be a sign that you are using too any threads. Do you have 1 thread per queue or do you use multithreading? How many fetcher threads do you use?

**Comment by jnioche** [comment]
No feedback. Closing for now
