### ISSUE TITLE
Compatibility mode issue (ES 8, RHLC 7.17.14)

### ISSUE THREAD

**Issue by aspexi** [DigitalPebble/storm-crawler#1108]
Storm Crawler: 2.10-SNAPSHOT
storm-client-version: 2.5.0
elasticsearch-rest-high-level-client: 7.17.14
elasticsearch-rest-client-sniffer: 8.8.1
ElasticSearch: 8.8.1

Compatibility mode enabled but I get this on _bulk queries:

```
java.io.IOException: Unable to parse response body for Response{requestLine=POST /_bulk?timeout=1m HTTP/1.1, host=http://localhost:9200, response=HTTP/1.1 200 OK}
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
	at org.elasticsearch.action.DocWriteResponse.<init>(DocWriteResponse.java:116)
```

Also asked the same question here https://github.com/elastic/elasticsearch/issues/84173#issuecomment-1762929183

Any ideas why regardless correct header I'm still seeing NPE?

Moreover, by monitoring network traffic I noticed that after some minutes the compatibility header disappears from _bulk requests. No idea why this happens.

**Comment by jnioche** [comment]
Hi @aspexi - did you get to the bottom of this problem?

**Comment by jnioche** [comment]
Closing for now, please reopen if needed
