### ISSUE TITLE
FileSpout: spread the work based on the number of instances

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#1125]
The FileSpout is currently unaware of the number of instances it has. All of them are expected to process the same input; for this reason there is currently no benefit in having more than 1 instance.

There could be some gains in having more than 1 instance if the implementation was able to split the inputs based on that. A similar mechanism is used by the OpenSearch/Elasticsearch spouts to map an instance to a shard. In the case of Filespouts, it would be beneficial to classes extending it like  [WARCSpout](https://github.com/DigitalPebble/storm-crawler/blob/master/external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCSpout.java), which takes some processing to generate the inputs and could become a bottleneck.

The easiest approach would be to process only the lines where line number % instance num = 0 in the [populate buffer method](https://github.com/DigitalPebble/storm-crawler/blob/857bf09da6cb03a28ffab93623697494f5e69792/core/src/main/java/com/digitalpebble/stormcrawler/spout/FileSpout.java#L140). All the instances would be reading the same files but skipping the lines that are not for them.

**Comment by rzo1** [comment]
Sounds good to me.

Alternative approach would be to allow to read from multiple files and split on a "per-file" basis.

**Comment by jnioche** [comment]
Thanks @rzo1. Splitting on file gives you no guarantee that the content will be balanced, one could be tiny, the other one very large. It is also less flexible + practically the files are handled in the constructor but we don't know about the number of instances until we get to the init method.
