### ISSUE TITLE
custom DocumentID override is not capable in DeletionBolt

### ISSUE THREAD

**Issue by chhsiao90** [DigitalPebble/storm-crawler#1133]
What kind of issue is this?  Feature request

This feature was already implemented in #1028 and #1036 for indexer and status bolts, but not in deletion bolt.

**Comment by chhsiao90** [comment]
Please let me know if we'd  like to have this feature in deletion bolt and I can have a PR for it.

**Comment by rzo1** [comment]
> This feature was already implemented in https://github.com/DigitalPebble/storm-crawler/pull/1028 and https://github.com/DigitalPebble/storm-crawler/pull/1036 for indexer and status bolts, but in deletion bolt.

Feel free to open a PR for it.

**Comment by jnioche** [comment]
Thanks a lot @chhsiao90
