### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#1137]
mvn versions:display-dependency-updates 

[INFO]   org.opensearch.client:opensearch-rest-high-level-client ... 2.11.0 -> 2.11.1
[INFO]   com.amazonaws:aws-java-sdk-cloudsearch .......... 1.12.585 -> 1.12.616
[INFO]   com.amazonaws:aws-java-sdk-s3 ................... 1.12.585 -> 1.12.617
[INFO]   com.fasterxml.jackson.core:jackson-annotations ...... 2.15.2 -> 2.16.0
[INFO]   com.fasterxml.jackson.core:jackson-core ............. 2.15.2 -> 2.16.0
[INFO]   com.fasterxml.jackson.core:jackson-databind ......... 2.15.2 -> 2.16.0
[INFO]   com.ibm.icu:icu4j ....................................... 74.1 -> 74.2
~~[INFO]   com.squareup.okhttp3:okhttp ................. 4.12.0 -> 5.0.0-alpha.11~~
~~[INFO]   com.squareup.okhttp3:okhttp-brotli .......... 4.12.0 -> 5.0.0-alpha.11~~
[INFO]   javax.xml.bind:jaxb-api .................. 2.3.1 -> 2.4.0-b180830.0359
[INFO]   org.apache.logging.log4j:log4j-api ............. 2.20.0 -> 2.22.0
[INFO]   org.apache.logging.log4j:log4j-core ............ 2.20.0 -> 2.22.0
[INFO]   org.apache.logging.log4j:log4j-slf4j-impl ...... 2.20.0 -> 2.22.0
~~[INFO]   org.apache.tika:tika-core ........................ 2.9.1 -> 3.0.0-BETA~~
~~[INFO]   org.apache.tika:tika-parsers-standard-package .... 2.9.1 -> 3.0.0-BETA~~
[INFO]   org.jetbrains:annotations ........................... 24.0.1 -> 24.1.0
[[INFO]   org.jsoup:jsoup ..................................... 1.16.2 -> 1.17.1
](https://jsoup.org/news/release-1.17.1)[INFO]   org.mockito:mockito-core .............................. 5.7.0 -> 5.8.0
[INFO]   org.netpreserve:jwarc ............................... 0.28.3 -> 0.28.5
[INFO]   org.seleniumhq.selenium:selenium-chrome-driver ...... 4.15.0 -> 4.16.1
[INFO]   org.seleniumhq.selenium:selenium-remote-driver ...... 4.15.0 -> 4.16.1

**Comment by rzo1** [comment]
Wdyt about activating https://github.com/renovatebot/renovate - it seems to be better than dependabot.

**Comment by jnioche** [comment]
> Wdyt about activating https://github.com/renovatebot/renovate - it seems to be better than dependabot.

yes, why not.
