### ISSUE TITLE
upgrade io.confluent:kafka-avro-serializer:jar:1.0

### ISSUE THREAD

**Issue by pjfanning** [DigitalPebble/storm-crawler#1152]
This is a very out of date version of this jar and is being reported as having an unknown license in the third party jar list.

This project not appear to publish to maven central - only to 3rd party maven repos.

https://mvnrepository.com/artifact/io.confluent/kafka-avro-serializer?repo=confluent-packages

**Comment by jnioche** [comment]
thanks @pjfanning 
This should be raised at Apache Storm instead, as we inherit it from its [storm-hdfs module](https://github.com/apache/storm/blob/4d92ba3df5e7542a926b300624c549c2b97482e7/external/storm-hdfs/pom.xml#L260)

**Comment by rzo1** [comment]
Yeah, we should get rid of it in Storm. Feel free to open a Jira (and/or create a PR If you have some minutes). Otherwise, I can have a look at it inside of Storm too but might take a few days 🙃

**Comment by rzo1** [comment]
https://issues.apache.org/jira/browse/STORM-4035
