### ISSUE TITLE
Parse could generate output for more than one document 

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#117]
At the moment we get a 1:1 relationship between the input and output of a parsing step. We could have a 1:N instead and more than one document in the output.

This is done in Nutch 1.x where the [ParseResult class](https://github.com/apache/nutch/blob/trunk/src/java/org/apache/nutch/parse/ParseResult.java) is a `Map<String,Parse>` with the [Parse](https://github.com/apache/nutch/blob/trunk/src/java/org/apache/nutch/parse/Parse.java) object containing the text and metadata for a URL.

This is useful for instance when a document can be split into subdocuments e.g. posts in a forum thread and we can't or don't want to fetch the subdocuments individually.

**Comment by GuiForget** [comment]
:+1:  from me as we have product pages with multiple products on it
