### ISSUE TITLE
Add/Improve documentation on parsing

### ISSUE THREAD

**Issue by GuiForget** [DigitalPebble/storm-crawler#124]

**Comment by jnioche** [comment]
[https://github.com/DigitalPebble/storm-crawler/wiki/JSoupParserBolt] already describes the parsing bolt. We should have an additional wiki page for the ParseFilter. Apart from that what else did you have in mind @GuiForget?

**Comment by jnioche** [comment]
[[ParseFilters]] done

**Comment by jnioche** [comment]
Have just added a description of [https://github.com/DigitalPebble/storm-crawler/wiki/MetadataTransfer].

@GuiForget please let me know if there is anything else you want to add

**Comment by jnioche** [comment]
Closing. @GuiForget please reopen if necessary
