### ISSUE TITLE
Remove fetchqueue stuff

### ISSUE THREAD

**Issue by jakekdodd** [DigitalPebble/storm-crawler#126]
I think most, if not all, of the classes in that package are unused.

@jnioche do you have any clients that are using/examining those classes?

If not, should we remove everything outright? Or is there anything worth refactoring and keeping in the project?

**Comment by jnioche** [comment]
This is mostly old stuff dating from when I started work on SC. I can't remember myself how it is meant to be used and I don't think anyone uses it. Let's remove it unless someone objects within the next 48 hours.

**Comment by jakekdodd** [comment]
b5f305442fe648a5d734dbdf8f77ff5bef6c640c completed

**Comment by jnioche** [comment]
There are still config elements related to this [https://github.com/DigitalPebble/storm-crawler/blob/master/core/crawler-conf.yaml#L61] and Constants

**Comment by jakekdodd** [comment]
Thanks for catching that, will take care of it

**Comment by jnioche** [comment]
Fixed in [master 3995c78] Removed constants and configs from sharded queues + Tika #126
