### ISSUE TITLE
Tick tuple in SimpleFetcherBolt

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#133]
[https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/storm/crawler/bolt/SimpleFetcherBolt.java#L160]

@jakekdodd the tick tuples aren't needed, are they? Was it something you copied from the other FetcherBolt?

**Comment by jakekdodd** [comment]
Yep it was copied over from FetcherBolt, and no it's definitely not needed--I'll take care of it now

**Comment by jakekdodd** [comment]
b84231124f7c412074f9c5ce63157599f04bed01 closed
