### ISSUE TITLE
Selenium-based protocol implementation

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#144]
This should allow us to deal with the dynamic content. See discussion #142 
Ideally we'd want to be able to have actions/navigations either programmatically or via configuration.

We could use :
- [selenium](http://seleniumhq.github.io/selenium/docs/api/java/index.html) directly 
- or via [crawljax](https://github.com/crawljax/crawljax)
- [ghostDriver](https://github.com/detro/ghostdriver) with PhantomJS
- [chromedriver](https://code.google.com/p/selenium/wiki/ChromeDriver) via the Selenium API

**Comment by jnioche** [comment]
Use [jBrowserDriver](https://github.com/MachinePublishers/jBrowserDriver/)? 100% Java and headless.

**Comment by kkrugler** [comment]
I think jBrowserDriver required Java 8 - would that be an issue?

Also, in the past we used [HTMLUnit](http://htmlunit.sourceforge.net/), though not without challenges.

**Comment by jnioche** [comment]
@kkrugler could put that in a separate repo so that the requirement for Java 8 does not become necessary for core and the other modules. 

Nutch has a HTMLUnit-based protocol implementation I think but not sure it's been used much yet and I haven't heard on that. There's also a Selenium one.

**Comment by jnioche** [comment]
[Example of JS content](http://stackoverflow.com/questions/40784663/how-to-parse-a-javascript-object-from-a-html-page-i-crawl)

**Comment by rkrombho** [comment]
Maybe [Geb](http://www.gebish.org/)?

It's very easy to use and based on Selenium WebDriver which means it supports all browser that have a Driver implementation.
It would mean that users could theoretically decide if they want to do headless (e.g. HtmlUnitDriver, PhantomJSDriver), go with a real browser or to use Selenium Grid with a variety of different browsers.

I did some very intensive integration testing with Geb (including waiting for AJAX responses etc.) and it is absolutely awesome.
Would be easy to let the user provide Groovy/Geb scripts that are executed against Page context that is currently being crawled but I have no Idea how this could work with the Protocol Interface.

**Comment by raaz1234** [comment]
Hi @jnioche - curious to know if the current version of stormcrawler supports this Ajax/Dynamic content parsing?

Thanks
Raj

**Comment by jnioche** [comment]
Hi @raaz1234, see branch https://github.com/DigitalPebble/storm-crawler/tree/jBrowserDriver. Not yet merged but please give it a try

**Comment by owenrh** [comment]
Hi @jnioche - is it just a case of configuring _http.protocol.implementation_ to use the JBrowserProcotol? Or is more needed to make this work?

**Comment by jnioche** [comment]
Hi @owenrh (am sitting at your desk, will try not to leave crumbs). Yes, should be just that indeed!

**Comment by jnioche** [comment]
@owenrh please have a look at #457

**Comment by owenrh** [comment]
@jnioche ha, thanks for the msgs, had an error on my inbox filters so I missed them. Will check it out, ta.

**Comment by jnioche** [comment]
@owenrh see also [http://digitalpebble.blogspot.co.uk/2017/04/crawl-dynamic-content-with-selenium-and.html]
