### ISSUE TITLE
Remove external/metrics?

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#160]
unless anyone uses it of course.

@DigitalPebble/committers-crawler thoughts on this?

**Comment by jorgelbg** [comment]
:+1: I don't see any problem

**Comment by jnioche** [comment]
Thanks
@DigitalPebble/committers-crawler anyone else?
Marking as 0.6

**Comment by jakekdodd** [comment]
Yeah should be OK to remove it

**Comment by jnioche** [comment]
done in [e088b7106d5f5b4b27c893e0a91d050c01d3168f]
thanks!
