### ISSUE TITLE
Metadata needs to be made immutable before emitting

### ISSUE THREAD

**Issue by jakekdodd** [DigitalPebble/storm-crawler#164]
We're getting ConcurrentModificationExceptions on Metadata instances while they're being serialized by Kryo.

According to the Storm docs, all values emitted in a tuple need to be immutable. This bug seems to rear its head when a Metadata instance is emitted from a bolt, and then subsequently modified later in the execute method coincident with Kryo serialization. We've seen this happen in a few places, but most commonly this exception occurs in a StatusStreamBolt that sits downstream of a parser bolt.

Because the StatusStreamBolt isn't actually modifying the metadata--just emitting, and thus serializing it--I believe this happens when a parser bolt and StatusStreamBolt are running on the same JVM.

In any case, the right way to handle this is to always emit an immutable defense snapshot of Metadata. I'd propose a `.copy()` or `.snapshot()` method on Metadata that would return a Guava ImmutableMap and a `.fromSnapshot()` method or something equivalent that returns a Metadata instance from an ImmutableMap

**Comment by jnioche** [comment]
When would fromSnapshot be needed? Would we have to change code to call .snapshot() every time we emit a Metadata? or can do that within Metadata so that it gets called by the serialization mechanism.

Ideally we'd want to find where in the code those Metadata instances survive the emission, because they shouldn't really.

**Comment by jorgelbg** [comment]
+1 on finding where in the code this is happening, it would be very
helpful.

**Comment by jakekdodd** [comment]
> When would fromSnapshot be needed?

When converting an ImmutableMap to Metadata after using `tuple.getValueByField()`. The alternative would be to have `.snapshot()` return a defense copy of Metadata, and then we could do `Metadata metadata = (Metadata) tuple.getValueByField("md")` as usual. This would still be a mutable object, however.

> Would we have to change code to call .snapshot() every time we emit a Metadata?

Unfortunately, yeah =/

> Ideally we'd want to find where in the code those Metadata instances survive the emission, because they shouldn't really.

>+1 on finding where in the code this is happening, it would be very
helpful.

Any time we emit metadata in a tuple, and then continue through the `execute()` method where we potentially perform operations on the metadata. As for where that happens, exactly, we'd have to do a full review of every single bolt to figure that out. I think we should, just so we're aware. Unfortunately the stack trace looks identical to the one described [here](https://storm.apache.org/documentation/Troubleshooting.html), so I don't have the exact location in the topology where the concurrent modification happens--only the name of the bolt where the serialization is happening and the exception is thrown.

**Comment by jnioche** [comment]
What about having a poor-man's implementation of immutability so that the underlying implementation of the Map does not change - which IIUC would save us having to do fromSnapshot(). We could add a method to turn the Metadata into an immutable state (e.g. `lock()`) and call that prior just before we emit so that we'd get the exception not in the serialization process but in wherever the Metadata instances are used when they shouldn't? That should help us find where in the code our problems are.

I see it as a debugging mechanism more than anything else. It could be used to detect such issues and avoid having to do a defensive copy when emitting.

**Comment by jakekdodd** [comment]
https://storm.apache.org/apidocs/backtype/storm/task/OutputCollector.html

ctrl +f "The emitted values must be immutable." :smiley: 

I'm not sure how the `lock()` mechanism would help us find the source of the problem. We would need to unlock the Metadata instance after Kryo has finished the serialization--how would we know when that happens?

We don't have to change the underlying implementation of the Map itself (the `md` member of Metadata). The `snapshot()` method would just return a new `ImmutableMap` object with a copy of `md`'s data. The `fromSnapshot()` method would copy all of an ImmutableMap's data into the mutable `md` of a new Metadata instance.

The other alternative I gave, to have the `snapshot()` method just return a new copy of Metadata (different object, same data) would obviate the need for a `fromSnapshot()` method to reconstruct a Metadata instance. But I still think this is unsafe

**Comment by jnioche** [comment]
> We would need to unlock the Metadata instance after Kryo has finished the serialization--how would we know when that happens?

We would not unlock it. The idea is that the serialization would work fine but whichever part of the code still operates on the metadata after it has been sent to the output would get an immutable exception. This way we'd be able to fix the problem in the first place, which is simpler than adding the snapshot/fromSnapshot logic.

**Comment by jnioche** [comment]
@jakekdodd I've just pushed a new branch called 164 which adds a lock mechanism to the Metadata and calls it in the JsoupParser whenever we emit a metadata. Could you please give it a try and see where you are getting UnsupportedOperationException? 

Again, I'd prefer not to have to enforce the lock/unlock mechanism systematically but just fix the incorrect use of Metadata.

**Comment by jnioche** [comment]
Not seen since and probably due to some incorrect bespoke code. Closing for now but could be reopened if anyone had the same problem

**Comment by nitindahiya** [comment]
Hi, I am also seeing ConcurrentModificationExceptions when i am using metadata map in a bolt.

So i have a bolt, let us say, AvroBolt, which needs to create avro record for every metadata key-value pair.

But iterating over the metadata and creating and emiting a avro record throws the concurrent modification exception, when running in local mode, not tried on distirbuted mode yet.

What is strange is the fact that the following code throws exception
``
        Metadata metadata = (Metadata) tuple.getValueByField("metadata");
        String jobId = tuple.getStringByField("jobId");
        Iterator<Map.Entry<String, String[]>> it = metadata.asMap().entrySet().iterator();
        Map<String, String[]> clonedMap = new HashMap<>();
        List<Avro> nfaList = new ArrayList<>();
        while (it.hasNext()) {
            Map.Entry<String, String[]> pair = it.next();
            clonedMap.put(pair.getKey(), pair.getValue());
            }
``
but the code below does not
``
        Metadata metadata = (Metadata) tuple.getValueByField("metadata");
        String jobId = tuple.getStringByField("jobId");
        Iterator<Map.Entry<String, String[]>> it = metadata.asMap().entrySet().iterator();
        Map<String, String[]> clonedMap = new HashMap<>();
        List<Avro> nfaList = new ArrayList<>();
        while (it.hasNext()) {
            Map.Entry<String, String[]> pair = it.next();
            System.out.print(pair.getKey());
            System.out.print(pair.getValue());

            }
``

I just can't assign the key/val to any variable.

**Comment by jnioche** [comment]
@nitindahiya I don't think this is related to the issue we were discussing at the time, if it did, you'd have the same problem in the second code. 

Not clear why this would happen on the clonedMap either.
