### ISSUE TITLE
NPE in function MetadataTransfert.filter()

### ISSUE THREAD

**Issue by ludovic-boutros** [DigitalPebble/storm-crawler#168]
Hi,

the parameter 'metadata' can be null in the function MetadataTransfert.filter().
It throws a NPE later.

Just adding the test and returning 'md' fix this issue.

**Comment by jnioche** [comment]
@ludovic-boutros did you get the NPE after I reverted your PR? Would be good to find where we get a null metadata.

**Comment by ludovic-boutros** [comment]
Not yet. I will try soon.

**Comment by ludovic-boutros** [comment]
Ok I reproduce the issue while running the Solr seed injector example. 
Will try to figure out what's wrong here.

**Comment by ludovic-boutros** [comment]
It seems that the FileSpout emits null metadata...

**Comment by jnioche** [comment]
So this would mean that [https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/storm/crawler/bolt/URLPartitionerBolt.java#L69] should also check for the value of metadata. In the case you found we were emitting a field metadata but with a null value. I'll fix this.

**Comment by jnioche** [comment]
@ludovic-boutros please close this issue if you are confident that the problem is now solved. Thanks
