### ISSUE TITLE
Fix Solr module documentation (commit size parameter)

### ISSUE THREAD

**Issue by ludovic-boutros** [DigitalPebble/storm-crawler#182]
The documentation of the Solr external storage module contains batch and commit size parameters.
They have been removed since the usage of autoCommit/autoSoftCommit in Solr.

**Comment by jorgelbg** [comment]
I'm going to commit the change to the README in the afternoon.

**Comment by jnioche** [comment]
@jorgelbg could you please amend the README file? Thanks!

**Comment by jnioche** [comment]
Fixed in #189
