### ISSUE TITLE
[SOLR] Compare SOLR module with one from Storm and Lucid

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#192]
SOLR connector [apache/storm#665]

@jorgelbg did you know about that?

**Comment by ludovic-boutros** [comment]
The main differences I can see at first glance are:
- I like the commit strategy abstraction and the ack management (A batch is acked (or not) in globality)  
- I do not like the fact that only hard commit seems to be used (This should be configurable)

**Comment by jorgelbg** [comment]
I didn't know about this, looks very interesting on a more closer look:

* Only provide support for SolrCloud and no way of using a non distributed Solr server
* Provide an abstraction/mapping layer that use some endpoints to fetch the Solr schema
* The implemented commit strategy is based on a document count threshold
* The ack/fail mechanism uses a queue when the commit is issued against Solr, then the queued tuples are acked/failed (the entire batch)

**Comment by jnioche** [comment]
There is also one from Lucid [https://github.com/lucidworks/storm-solr]

**Comment by jnioche** [comment]
Closing for now, hasn't been much interest in the SOLR module lately.
