### ISSUE TITLE
Add default config file in resources

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#193]
We currently have a class listing some of the constants and an [example of conf file](https://github.com/DigitalPebble/storm-crawler/blob/master/core/crawler-conf.yaml) for users to use at runtime. 

It would be good to have a default config file in the resources which would be used to list all the known configs as well as their default values. This would get loaded automatically  when using a [ConfigurableTopology](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/storm/crawler/ConfigurableTopology.java) and the values would then be overridden by whatever the users specify in their custom conf files.

**Comment by jorgelbg** [comment]
+1 I don't see any reason not to have this, it would make things even easier to understand where the default value is coming for a given setting.

**Comment by jnioche** [comment]
Implemented in [22d7e19]
