### ISSUE TITLE
FileSpout chokes on very large files

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#196]
Instead of loading everything into memory it could buffer lines and read only when needed.

**Comment by jnioche** [comment]
thanks @mattburns

**Comment by jorgelbg** [comment]
I took a shot at this issue but using `FileUtils.lineIterator` from commons-io instead https://github.com/jorgelbg/storm-crawler/commit/e088a2560da7b4bb1c78ed4f151d0b6add24ad9b
