### ISSUE TITLE
HTTP protocol should allow to limit amount of content fetched

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#206]
The previous implementation we had which was taken from Nutch could do that but not the one we currently have. This is useful for cases where the URL points to a multimedia stream for instance.

**Comment by kkrugler** [comment]
By "limit content fetched" do you mean it shouldn't fetch content that has a mime type other than ones of interest? Or is there some multi-part content where you want to skip pieces of the content stream?

**Comment by jnioche** [comment]
Simply that it should stop fetching past a given byte length, similar to what `http.content.limit` does in Nutch.

**Comment by kkrugler** [comment]
For the SimpleHttpFetcher in bixo (not sure about what's in crawler-commons) we have a default limit, and a per-mime type limit. That way you can avoid truncating binary content (like PDFs, Word docs, etc) where the parser will choke if the content is truncated. That still leaves the issue of gzipped content, where truncation also causes a problem

**Comment by jnioche** [comment]
Makes sense to truncate per mime type indeed. I can see how you do that in [https://github.com/bixo/bixo/blob/master/src/main/java/bixo/fetcher/SimpleHttpFetcher.java#L460].
Doing that indiscriminately would be good enough for now, ideally without having to hack the HttpClient code too much.

**Comment by jorgelbg** [comment]
+1
