### ISSUE TITLE
Store the metadata field in the status collection to be searchable

### ISSUE THREAD

**Issue by jorgelbg** [DigitalPebble/storm-crawler#207]
Similar to #197 #201 but for Solr, in this case since Solr have a different approach to nested objects/documents, perhaps a better approach could be to flatten the metadata field using a prefix, combined with a dynamic setting? 

Thoughts on this are welcome, I think that using nested documents could be an overkill, plus since Solr doesn't "hide" the child documents the status collection will be packed with additional metadata/child documents.

**Comment by ludovic-boutros** [comment]
@jorgelbg That would be great. I also agree with the flattening of the metadata.

**Comment by jnioche** [comment]
+1 thanks!

**Comment by jnioche** [comment]
@jorgelbg shall we mark it for release 0.7?

**Comment by jorgelbg** [comment]
@jnioche yes sure! I'll submit a PR later today
