### ISSUE TITLE
[SOLR] Check that not more than one instance of the Spout exists

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#213]
Similar to what we do in [ElasticSearchSpout](https://github.com/DigitalPebble/storm-crawler/blob/master/external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/ElasticSearchSpout.java#L118). Having more than one instance of the SOLR Spout would potentially send the same URLs down the topology more than once. 
Later on we could enforce sharding based on hostname/domain etc... and make so that there is one instance of the spout per shard. 

@jorgelbg what do you think?

**Comment by jorgelbg** [comment]
This sounds great! I see one additional outcome, since we'll have 1 spout per shard we can add the ability to also use this shard keys for routing withing SolrCloud. We discussed about this some time ago, and even if SolrCloud does the routing automatically, this could be useful on some cases.
