### ISSUE TITLE
StatusUpdaterBolts must be able to ack/fail explicitly

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#216]
The class [AbstractStatusUpdaterBolt](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/storm/crawler/persistence/AbstractStatusUpdaterBolt.java) currently acks each tuple after calling the store method. Some implementations e.g. ElasticSearch one have a buffering client which means that we don't know instantly whether an update has succeeded or failed. We could change the abstract class so that extensions can fail or ack themselves.

**Comment by w0mbat** [comment]
I also experienced the problem in the last couple of days where we had some connection issues with ES and the tuples were gone

**Comment by jnioche** [comment]
you mean they'd been acked regardless of whether the ES indexing has succeeded? Maybe try the branch in #241

**Comment by w0mbat** [comment]
@jnioche yes, they were acked although indexing failed. Thanks - Will try later
