### ISSUE TITLE
Change groupId in pom.xml

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#218]
We currently use `<groupId>com.digitalpebble</groupId>`

but according to [https://maven.apache.org/guides/mini/guide-naming-conventions.html] this should be used to 'identify your project uniquely across all projects'.

We should probably use something like  `<groupId>com.digitalpebble.stormcrawler</groupId>`  or `<groupId>com.digitalpebble.storm-crawler</groupId>` instead.

If so what should we use for the  artifactId? Do we need to repeat 'storm-crawler' as we currently do e.g. `<artifactId>storm-crawler-elasticsearch</artifactId>` or just go for `<artifactId>elasticsearch</artifactId>`?

@DigitalPebble/committers-crawler thoughts please!

**Comment by ludovic-boutros** [comment]
Apache Camel repeats 'camel' for the different modules and I like it.

**Comment by jnioche** [comment]
@ludovic-boutros thanks. storm do that for the external modules too. 

I am leaning towards using 'stormcrawler' instead of 'storm-crawler' in both the groupid and artefactid - any thoughts on this?

**Comment by jnioche** [comment]
[master d349dc2] Change groupId in pom.xml #218
