### ISSUE TITLE
JsoupDOMBuilder not copying in-line JavaScript and CSS Styles

### ISSUE THREAD

**Issue by rkrombho** [DigitalPebble/storm-crawler#219]
The Method `com.digitalpebble.storm.crawler.parse.JSoupDOMBuilder.createDOM` does not copy data from JSoup DataNodes (http://jsoup.org/apidocs/org/jsoup/nodes/DataNode.html) into the resulting DOM.

This causes the resulting DOM to not contain any JavaScript of in-line CSS Style text.
This prevents ParseFilters from being able to analyze contents of `script` tags.

**Comment by jnioche** [comment]
Thanks @rkrombho. Do you have a patch for this or a unit test we could use?

**Comment by rkrombho** [comment]
Yes, will raise a pr when I find the time

**Comment by jnioche** [comment]
@rkrombho  should be fixed. See unit test included in patch. Please reopen if it does not work as expected
