### ISSUE TITLE
[Elasticsearch] upgrade to version 5

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#221]
Amazon Elasticsearch does not support the native protocol and requires a REST based client like [Jest](https://github.com/searchbox-io/Jest). It would be good to have that as well

**Comment by jnioche** [comment]
[Elasticsearch 5](https://www.elastic.co/blog/elastic-stack-release-5-0-0-alpha-4) will provide 

> "a low-level Java HTTP/REST client. It provides a simple HTTP client with minimal dependencies, which handles sniffing, logging, round robinning of requests, and retry on node failure."

**Comment by jnioche** [comment]
Search-time field collapsing with paging is EXACTLY what we need for our spouts!

[https://www.elastic.co/blog/this-week-in-elasticsearch-and-apache-lucene-2017-01-30]

**Comment by jnioche** [comment]
Am having problems with the log dependencies which conflict with the ones in Storm

https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/_using_another_logger.html

Worth noticing that [ES-Hadoop](https://github.com/elastic/elasticsearch-hadoop) does not use the Java client (which causes the log dependency) but handles things through REST.

**Comment by kkrugler** [comment]
Elastic is pushing hard for everyone to transition to the REST client, versus the Java (Transport or Node) client.

**Comment by jnioche** [comment]
Fixed the log dependency problem by updating the versions in Storm for the branches [1.0.x](https://github.com/apache/storm/pull/1946) and [1.x](https://github.com/apache/storm/pull/1947). There is also an open PR for [2.x](https://github.com/apache/storm/pull/1969). Have used the branch _es5_ and it works great. Might wait for Elasticseach 5.3 to be released as it will contain the field collapsing mentioned earlier. Will open a sub-branch specifically for that and test the perfs vs using aggregations.
