### ISSUE TITLE
MaxDepthFilter not considered correctly?

### ISSUE THREAD

**Issue by w0mbat** [DigitalPebble/storm-crawler#222]
Hey folks,

I cloned the repo, set the MaxDepthFilter to 10 and removed all urls from RandomURLSpout but one. Afterwards I started the Topology locally and expected to discover the urls and crawl the site until maxDepth of 10 is reached or no new URLs are available.

But what I see is that it only crawls the first page and then I see no more crawling activity.

Any thoughts?

**Comment by jnioche** [comment]
Hi @w0mbat
 
That's normal.  In the example [CrawlTopology](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/storm/crawler/CrawlTopology.java) the StdOutStatusUpdater just dumps the URLs discovered to the standard output. They do not get added to the Spout.

In a real life topology you'd use an external storage e.g. Elasticsearch, MySQL, RabbitMQ etc... see the corresponding modules for examples and instructions. You'd also connect to an indexer like SOLR or ES.

Now what we could do would be to modify the RandomURLSpout (e.g. with a public static Map) containing the URLs and Metadata and add a StatusUpdater for it. Obviously this would work only in local mode when both the spout and updater are in the same JVM.

Does this make sense?

**Comment by w0mbat** [comment]
Hey @jnioche

Thanks for the quick feedback!
I quickly hacked on the proposed solution and yes, it works!
Sure, its currently only to see how things are playing together and whats possible!

Best

Daniel

**Comment by jnioche** [comment]
> I quickly hacked on the proposed solution and yes, it works!

cool. Feel free to send a PR if you could spare the time. It would be a useful feature
