### ISSUE TITLE
[status] subscribes from non-existent stream: [status] of component [index]

### ISSUE THREAD

**Issue by GasparPizarro** [DigitalPebble/storm-crawler#226]
I'm working with storm-crawler-core-0.8-SNAPSHOT and storm-crawler-solr-0.6 and cannot plug the status bolt with the indexer bolt through the `StatusStreamName` stream, even though the code in AbstractIndexerBolt says  

    declarer.declareStream(com.digitalpebble.storm.crawler.Constants.StatusStreamName, new Fields("url", "metadata", "status"));

I'm receiving this error:

    backtype.storm.daemon.nimbus - Topology submission exception. (topology name='crawl') #<InvalidTopologyException InvalidTopologyException(msg:Component: [status] subscribes from non-existent stream: [status] of component [index])

My topology is this:

    public class CrawlTopology extends ConfigurableTopology {

        public static void main(String[] args) throws Exception {
            ConfigurableTopology.start(new CrawlTopology(), args);
        }

        @Override
        protected int run(String[] args) {
            TopologyBuilder builder = new TopologyBuilder();
            builder.setSpout("spout", new QueueSpout()); //Receives messages from a amqp queue
            builder.setBolt("partitioner", new URLPartitionerBolt()).shuffleGrouping("spout");
            builder.setBolt("fetch", new FetcherBolt()).fieldsGrouping("partitioner", new Fields("key"));
            builder.setBolt("parse", new JSoupParserBolt()).localOrShuffleGrouping("fetch");
            builder.setBolt("index", new IndexerBolt()).localOrShuffleGrouping("parse");
            builder.setBolt("status", new MongoStatusUpdater()) //Sends received tuples to a mongo database
                    .localOrShuffleGrouping("parse", Constants.StatusStreamName)
                    .localOrShuffleGrouping("index", Constants.StatusStreamName);
            return submit("crawl", conf, builder);
        }
    }

**Comment by jnioche** [comment]
storm-crawler-solr-0.6 is not compatible with the change in AbstractIndexerBolt [https://github.com/DigitalPebble/storm-crawler/issues/190]. You should use storm-crawler-solr-0.8-SNAPSHOT instead

**Comment by jnioche** [comment]
@GasparPizarro 

BTW MongoStatusUpdater should also subscribe to the tuples on status stream coming from the Fetcher, you'll never get notified of redirections otherwise
