### ISSUE TITLE
Replace HTTP protocol implementation

### ISSUE THREAD

**Issue by jakekdodd** [DigitalPebble/storm-crawler#23]
Before I did anything with this, wanted to check and see if there was a reason why HTTP 1.0 was hardcoded. Right now, line 167 of HttpResponse sets the protocol version to 1.0, regardless of whether ``http.useHttp11: true`` is set in the configuration:

```java
StringBuffer reqStr = new StringBuffer("GET ");
            if (http.useProxy()) {
                reqStr.append(url.getProtocol() + "://" + host + portString
                        + path);
            } else {
                reqStr.append(path);
            }

            reqStr.append(" HTTP/1.0\r\n");
```

Is this intentional?

**Comment by jnioche** [comment]
I've made good progress on a HTTP implementation based on  [http://hc.apache.org/]. Will commit post 0.5 release
