### ISSUE TITLE
Custom priority

### ISSUE THREAD

**Issue by mattburns** [DigitalPebble/storm-crawler#230]
Allow a config setting to use a custom priority field instead of nextFetchDate or random. For example, you could choose the field in the status index you wish to sort by. Something like `es.status.custom.sort: "priority"`

That way, when you populate the status index, you can just thing to the front of the queue by setting their priority to `1`.

As a happy side effect, this can solve the current random sorting problem I've been seeing of `field_data` being filled with hashes of the `_uid`. If you want random sorting then you could simply store the hash of the `_uid` in the `priority` field then custom sort on that.

**Comment by jnioche** [comment]
Added es.status.sort.field: "nextFetchDate" for ElasticSearchSpout 
AggregationSpout could already sort within a bucket with `es.status.bucket.sort.field: "nextFetchDate"`
