### ISSUE TITLE
Tika NoSuchMethodError

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#292]
This occurred after moving to 1.13. The pom gets the right version though. This does not happen with 1.12, will revert to that

```
java.lang.NoSuchMethodError: org.apache.tika.parser.ParseContext.getDocumentBuilder()Ljavax/xml/parsers/DocumentBuilder; at org.apache.tika.parser.pdf.PDFParser.loadDOM(PDFParser.java:602) at org.apache.tika.parser.pdf.PDFParser.extractMetadata(PDFParser.java:203) at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:136) at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:281) at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:281) at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120) at com.digitalpebble.storm.crawler.tika.ParserBolt.execute(ParserBolt.java:185)
```

**Comment by tballison** [comment]
Is this a bug in Tika or a version conflict in the storm-crawler ecosystem?  I'd strongly encourage using 1.13 at this particular point in the code because of this [CVE](http://seclists.org/oss-sec/2016/q2/413)

**Comment by jnioche** [comment]
Thanks @tballison. Will look into it again.

**Comment by jnioche** [comment]
Can't reproduce the problem. I can use Tika 1.13 in a topology running in Eclipse as well as using the Storm command both in local and deployed mode. Marking as closed for now.
