### ISSUE TITLE
Xpath expressions don't match when element name is set

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#31]
As shown in the test [https://github.com/DigitalPebble/storm-crawler/commit/7cf89baec8297fc4e725d6d06be5f1145d6194c1], the XPathFilter does not extract the data when an element name is specified.

**Comment by GuiForget** [comment]
This test passes when I use the JSoupParserBolt... So seems like another Tika Parser issue... I'll try to dig into it
