### ISSUE TITLE
Add WARC module to main repo

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#313]
It is currently used in [https://github.com/DigitalPebble/sc-warc] - which works on HDFS only.
We might want it in core, irrespective of where it is being stored onto. For instance we might have add code for storing into Amazon S3.

**Comment by jnioche** [comment]
or move the whole warc repo as a submodule of SC and make the format class reusable by other implementations?

**Comment by sebastian-nagel** [comment]
Although based on HDFS it allows writing to a local file. Writing to S3 should also be possible via HDFS using `s3a://` as scheme/protocol and given that s3a support libraries are installed.

Having the WARC bolt in the main repo would simplify to synchronize its dependencies with that of stormcrawler.

**Comment by jnioche** [comment]
Seems to be some consensus on https://twitter.com/stormcrawlerapi/status/788021645957009410
I will port the code to the main repo.
