### ISSUE TITLE
HTTP protocol : store request and response headers verbatim in metadata 

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#317]
[WARCRecordFormat](https://github.com/DigitalPebble/sc-warc/blob/master/src/main/java/com/digitalpebble/stormcrawler/warc/WARCRecordFormat.java#L66) uses the value of the metadata key `_response.headers_` to include the HTTP headers in the WARC representation. The  WARCTypeValue  would then be 'response' instead of `resource`.

Similarly we'll need to store the request for [https://github.com/DigitalPebble/sc-warc/issues/1]

**Comment by jnioche** [comment]
Storing the request headers is not easily doable with httpclient as the user agent info is not accessible from the httpget object.

**Comment by anjackson** [comment]
In case it's useful in the future, I think [this is how Heritrix does it](https://github.com/internetarchive/heritrix3/blob/124907341f8b4b3e921c03721d77d52b33ea96e0/modules/src/main/java/org/archive/modules/fetcher/FetchHTTPRequest.java#L628). i.e. it wraps the input and output streams at the socket level and records what happens so it can be picked apart afterwards.
