### ISSUE TITLE
SimpleFetcherBolt not encoding spaces

### ISSUE THREAD

**Issue by ndtreviv** [DigitalPebble/storm-crawler#321]
We've come across several `illegal character in path` errors in our logs, eg:
```
java.lang.IllegalArgumentException: Illegal character in path at index 48: http://www.laznianowa.pl//upload/files/molinezja fot.g.gazik 1.jpg
```

In this case, the URL is sort-of fine, so long as spaces are URL encoded.

Stack trace example:
```
java.lang.IllegalArgumentException: Illegal character in path at index 50: http://www.laznianowa.pl//upload/files/fakir9_fot. grzegorz ziemiaski.jpg
	at java.net.URI.create(URI.java:859) ~[?:1.7.0_101]
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69) ~[stormjar.jar:?]
	at com.digitalpebble.storm.crawler.protocol.httpclient.HttpProtocol.getProtocolOutput(HttpProtocol.java:127) ~[stormjar.jar:?]
	at com.digitalpebble.storm.crawler.bolt.SimpleFetcherBolt.execute(SimpleFetcherBolt.java:333) [stormjar.jar:?]
```

Is there something we need to do to ensure that the spaces are encoded before SimpleFetcherBolt attempts to fetch them?

**Comment by jnioche** [comment]
Hi @ndtreviv 
This is not handled at the Fetcher level or even by the Protocol but through the URL filtering. The [BasicURLNormalizer](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/stormcrawler/filtering/basic/BasicURLNormalizer.java) should already do it, you just need to add it to the URL filtering configuration.
