### ISSUE TITLE
Documentation: Kibana dashboard import and typos

### ISSUE THREAD

**Issue by sebastian-nagel** [DigitalPebble/storm-crawler#323]
- to import the dashboard config kibana.json: need to create index patterns first, see #322
- typos in the Wiki, see [diff](https://github.com/sebastian-nagel/storm-crawler/wiki/Configuration/_compare/6481df1e1107a982e4038792ee3c6aea1fc9625f...aa7e898b801ffcbe5d9ed0a7bdd2fbc491a5c0ba?diff=unified)

**Comment by jnioche** [comment]
Wiki fixed, thanks!
