### ISSUE TITLE
Should 403 response codes result in status of ERROR?

### ISSUE THREAD

**Issue by owenrh** [DigitalPebble/storm-crawler#329]
The [_Status.fromHTTPCode_ ](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/stormcrawler/persistence/Status.java) method currently returns a _FETCH_ERROR_ status for 403 response codes. Would it make more sense to return an _ERROR_ status as a 403 seems like a permanent crawl error?

I guess the same could maybe said for 404s? Possibly, maybe, or not.

**Comment by jnioche** [comment]
It would be logical to do so but in practice a 403 is not always a definitive error - it is sometimes used when you hit a server too hard and get temporarily blacklisted. When trying the same URL again a bit later you get the URL fine. Same for a 404, under stress some servers would throw them but not when working in a normal load.
There is (or at least I think so) a logic in the scheduler to turn a FETCH_ERROR into a hard ERROR after n attempts. ERROR means "don't even try again" e.g. something that breaks the parser whereas FETCH_ERROR gives it another chance.
PS: can you post questions on Stackoverflow with the label stormcrawler? That would boost the visibility of the project there :-)

**Comment by owenrh** [comment]
Yeah, I suspected it might not be as trivial as that. 

Just looking at the data some test data with the new metadata.lastProcessedDate I can see we're getting throttled with 404s. I think in terms of increasing our throughput we're going to have to become host-aware and think about some other options. Hmm, needs a bit more thought : )

(Will defo Stackoverflow it next time!)
