### ISSUE TITLE
Add intelligence to AggregationSpout re:host availability

### ISSUE THREAD

**Issue by ndtreviv** [DigitalPebble/storm-crawler#334]
Currently, if there are a number of URLs associated with a single domain, and that domain itself either no longer exists, or has a robots.txt rule denying access, there is no intelligence to handle that. The spout will emit all URLs to be processed regardless.

There is a certain amount of handling to cater for this (eg: cached robots rules) to ensure that when they are processed, they are processed quickly, but this could potentially be improved.

This is an enhancement request, therefore, for domains in the status index to be given a priority/scoring system that is updated with feedback from the fetcher bolt. 

If the URL 404s, or has an SSL error, and the root domain does the same, then the priority/score should be reduced.
If the robots.txt denies access, again the priority/score should be reduced.

The "Top N Hosts" query in the AggregationSpout should then take this priority/scoring into account.

Other things to consider are: 
- How many times a request to the root domain should be retried (in case of bad load-balancer, for example)
- How long before those hosts are retried once de-prioritised?
- How many times the hosts should be retried before giving up entirely?

There are probably a bunch of other things that need discussing when you get into the weeds of it, but this sort of intelligence would definitely improve overall throughput and would be a massive boon.

**Comment by jnioche** [comment]
Implemented  in "Pluggable URLBuffer and Hybrid Elasticsearch spout (#752)"
