### ISSUE TITLE
Fix links to code in Wiki

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#344]
Since we changed the packages to stormcrawler, all links to storm/crawler should be rewritten

**Comment by valencik** [comment]
I was going to do this myself as a small thank you, but it appears GitHub doesn't support pull requests on Wikis.
You can however clone the wiki, edit locally, and push the changes.
So the following should work (tested locally on Mac OS X):

```
git clone https://github.com/DigitalPebble/storm-crawler.wiki.git
cd storm-crawler.wiki
sed -i '' 's:digitalpebble/storm/crawler:digitalpebble/storm-crawler:' *.md
```

There are 36 instances of `storm/crawler` that should change.
However this will also add newlines to the ending of files without them, so you'll end up with more than 36 line changes.

Thanks!

**Comment by jnioche** [comment]
Thanks @valencik 

I had to use 
`sed -i 's:digitalpebble/storm/crawler/:digitalpebble/stormcrawler/:' *.md` without hyphen and do a manual fix in one of the files, but this seems to have done the trick.
