### ISSUE TITLE
Handle redirections via meta tag

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#350]
We currently don't handle redirs in html, a page such as the one below gets treated as fetched and gets indexed with an empty content, outlinks do not get discovered

```
 <html>    
  <head>      
    <meta http-equiv="refresh" content="0;URL=http://www.apollocolors.com/site" />    
  </head>    
</html>     
```

at the very least we should treat the link as discovered but ideally the main URL should get REDIRECTIOn

**Comment by prokopidis** [comment]
I think that a content attribute with one or more spaces between `;` and `URL` like `content="0; URL=http://www.apollocolors.com/site"` is not handled by RefreshTag. Perhaps the class could use a pattern match like

```
    private static XPathExpression expression;
    static Matcher matcher = Pattern.compile("^.*;\\s*URL=(.+)$", Pattern.CASE_INSENSITIVE).matcher("");
...
        if (StringUtils.isBlank(value))
            return null;
        // 0;URL=http://www.apollocolors.com/site
        if (matcher.reset(value).matches()) {
            return matcher.group(1);
        }
...
```

**Comment by jnioche** [comment]
thanks @prokopidis. Good point, would you mind opening a PR for this with a test?
