### ISSUE TITLE
Tika parser may not be parsing embedded documents

### ISSUE THREAD

**Issue by tballison** [DigitalPebble/storm-crawler#358]
If calling Tika's parse() with 4 parameters (using the ParseContext), you need to add a Parser.class to the ParseContext to handle embedded documents.

See [TIKA-2096](https://issues.apache.org/jira/browse/TIKA-2096) for a proposal to fix our API in Tika 2.0, and for a list of other projects (including Tika!) that fell victim to this.

I'd open a PR, but I can't quickly see how to test Tika.  I'd recommend grabbing our [test_recursive_embedded.docx](https://git-wip-us.apache.org/repos/asf?p=tika.git;a=blob_plain;f=tika-server/src/test/resources/test_recursive_embedded.docx;hb=HEAD).

**Comment by jnioche** [comment]
Thanks @tballison, I've implemented your suggestion and created a test environment for Tika, which will be useful for other things as well.

Just to check that I understand it properly \: when dealing with embedded docs, is there a way to separate each individual subdoc or does it all get lumped up in a single object? StormCrawler can generate discrete subdocuments from an original one so we could use that.

**Comment by tballison** [comment]
Well, now that you mention it, :), see https://github.com/DigitalPebble/storm-crawler/issues/361.  Let me know if you have any questions.
