### ISSUE TITLE
Language ID filter

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#364]
It would be useful to have a language identification module running as a ParseFilter. Could use the one in Tika as a starting point.

**Comment by jnioche** [comment]
Tika now uses [https://github.com/optimaize/language-detector], we might as well use that directly. The dependency is 1.9MB in size. Should it be in the main repo though?

**Comment by kkrugler** [comment]
Side note - [Yalder](https://github.com/kkrugler/yalder) is another option that (in Tika 2.0) will likely be the default language detector (faster, better accuracy, more languages). But I've stalled out on getting a real release cut, so not ready for prime time yet.

**Comment by jnioche** [comment]
Thanks @kkrugler, will keep an eye on it.
