### ISSUE TITLE
Filtering : treat path parameters as query parameters

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#366]
> Each path segment may include a sequence of parameters, indicated by the semicolon ";" character.

such as 

[http://www.maroongroupllc.com/maroon/login/auth;jsessionid=8DBFC2FEDBD740BBC8B4D1A504A6DE7F]

Although quite rare, it should be possible to treat such path parameters as query parameters and filter them accordingly.

**Comment by kkrugler** [comment]
Feels like URL normalization should make its way into crawler-commons. This is a good example of all the "interesting" edge cases that we don't want everyone to have to independently find/support in every project.

**Comment by jnioche** [comment]
I completely agree @kkrugler. The next release will contain [https://github.com/crawler-commons/crawler-commons/blob/master/src/main/java/crawlercommons/filters/basic/BasicURLNormalizer.java] which is a good start but we should improve it with cases like this one.
