### ISSUE TITLE
Spouts : load results with a non-blocking call

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#371]
We currently block the nextTuple when executing an Elasticsearch query and as such prevent ack/fails to happen. Instead, we should execute the ES query with a non-blocking call and return as soon as possible. This would possibly require the access to the buffer to be synchronized and an additional check that we are not already querying.

**Comment by XciD** [comment]
I've done something similar on my spouts, as you say, in order to don't block `nextTuple`, `ack`and `fail` methods

I will try to generify

**Comment by jnioche** [comment]
That would be great. Thanks
