### ISSUE TITLE
URLs of Status.REDIRECTION in metadata.depth calculation

### ISSUE THREAD

**Issue by prokopidis** [DigitalPebble/storm-crawler#379]
Suppose SC is used to collect all content up to depth 1 from a site www.example.com and that this seed URL immediately leads via meta- or server-side redirection to www.example.com/en-us/. Does this mean that the latter will be the only entry with metadata.depth 1 in the status index and that "actual" depth 1 URLs will never be fetched? 

If yes, is there a way to change this behaviour (i.e. to skip the the redirection URL in metadata.depth calculation), maybe from the crawl configuration file?

**Comment by jnioche** [comment]
Correct, redirections are not treated differently from outlinks, see [https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/stormcrawler/util/MetadataTransfer.java#L162].

There is currently no way to circumvent this.
