### ISSUE TITLE
[ElasticSearch] The cluster.name parameter does not work from conf file

### ISSUE THREAD

**Issue by Laurent-Hervaud** [DigitalPebble/storm-crawler#392]
Connection with elasticsearch not working if cluster name different than elasticsearch.
The parameter cluster.name: "myclustername" (ex : es-stormcrawler) has no effect.
It's working only if your cluster name is elasticsearch (default)
The same for all 3 parameters (es.indexer.settings, es.metrics.settings, es.status.settings)

**Comment by jnioche** [comment]
Hi @Laurent-Hervaud. 

The way the cluster name is specified has changed since 1.2; as shown in [es-conf.yaml](https://github.com/DigitalPebble/storm-crawler/blob/master/external/elasticsearch/es-conf.yaml)

```
  es.status.settings:
    cluster.name: "blabla" 
```

Feel free to reopen this issue if necessary.

**Comment by Laurent-Hervaud** [comment]
I known but this parameter is not use properly. If the es cluster name different than elasticsearch, no query or index will work with ES. 
My conf :

  es.status.settings:
    cluster.name: "es-stormcrawler"

**Comment by jnioche** [comment]
I just checked and it worked fine for me. Could it be the formatting e.g. no spaces before cluster.name?

**Comment by Laurent-Hervaud** [comment]
It's work for me too. Sorry...

**Comment by jnioche** [comment]
No problem. Glad we found what the problem was

**Comment by Laurent-Hervaud** [comment]
Ok I found. Not working with StormCrawler Maven Archetype (version 1.2).
Resolved with 1.3 snapshot
