### ISSUE TITLE
[ElasticSearch] ES 2.4.x not support for dots in field names

### ISSUE THREAD

**Issue by Laurent-Hervaud** [DigitalPebble/storm-crawler#393]
Error in ES log : MapperParsingException[Field name [metadata.hostname] cannot contain '.']
The status index is not working with ES
Solution : modify parameter es.status.routing.fieldname in es-conf file (ex : es.status.routing.fieldname: "metadata_hostname")

https://www.elastic.co/guide/en/elasticsearch/reference/2.4/dots-in-names.html

**Comment by jnioche** [comment]
Thanks for reporting this @Laurent-Hervaud. This is due to a recent change I made since 1.2, will fix it shortly.

**Comment by jnioche** [comment]
@Laurent-Hervaud I've just pushed a fix for this. Could you give it a try and let me know if it fixes it? Thanks again for reporting this.

**Comment by Laurent-Hervaud** [comment]
@jnioche Ok, I have tested and it is fixed. Thanks
