### ISSUE TITLE
per url depth & regex filter

### ISSUE THREAD

**Issue by MyraBaba** [DigitalPebble/storm-crawler#399]
feature wish 👍 

There will be a very useful if we can submit the seed list with depth and url filter regex  per url as an option.

**Comment by jnioche** [comment]
Having a mechanism to set a non default max depth per seed is a good idea and the regex one could be useful too but would you mind giving me an example of that so that I can have a better picture of what you are trying to achieve?

**Comment by MyraBaba** [comment]
I have different type of urls (news , portal , blog etc.) So each one needs different follow rules.

Such as:

http://edition.cnn.com/ <http://edition.cnn.com/> 

I wan to follow only if url includes “politics”  at 4 level depth ie : http://edition.cnn.com/2017/01/04/politics/us-intelligence-trump/index.html <http://edition.cnn.com/2017/01/04/politics/us-intelligence-trump/index.html> 

so  the url seed could be :

  http://edition.cnn.com/ <http://edition.cnn.com/> , 4 , regex     

So I can crawl the url if it fits the regex pattern at level of depth.

If there is no depth  or regex parameter  it should be fall the system default.

ie:

http://edition.cnn.com/ <http://edition.cnn.com/> , 4    Follow to 4.level depth with system default url filter.

I hope I gave you an idea.


We found it that it will be very usefull if there is a such feature.

**Comment by jnioche** [comment]
@MyraBaba I have implemented your suggestion for the custom depth per URL, see [f46b1ab].
You can now specify 'max.depth=X' in the seed metadata; it will be passed on to the outlinks automatically.
Could you please give it a try? Thanks

**Comment by MyraBaba** [comment]
I will test soonest possible and let you know.

so seed list like this:

http://www.nccv.com , max.depth=3

right ?

**Comment by MyraBaba** [comment]
I made seed.txt  like   :   http://www.haberturk.com.tr , max_depth = 1

 made

it gaves error:  7871 [FetcherThread] ERROR c.d.s.b.FetcherBolt - Exception while fetching http://www.haberturk.com.tr , max_depth = 1


 obviously i missed something ?

**Comment by jnioche** [comment]
Check the topology code, unless you specified otherwise, the FileSpout uses com.digitalpebble.stormcrawler.util.StringTabScheme to deserialise from the text file. It expects tabs as separator between the URL and the key values.

**Comment by MyraBaba** [comment]
Thanks ..

I tested now with the TAB  both 1 depth and 2 depth for http://www.haberturk.com.tr
It  gave REDIRECTION and not followed for both 1 and 2 depth test.

here output
FYI

9849 [Thread-85-spout-executor[36 36]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 0 hits in 358 msec
11423 [FetcherThread] INFO  c.d.s.b.FetcherBolt - [Fetcher #20] Fetched http://www.haberturk.com.tr with status 302 in msec 49
11432 [FetcherThread] INFO  c.d.s.b.FetcherBolt - [Fetcher #20] Fetched http://www.haberturk.com.tr with status 302 in msec 60
11466 [FetcherThread] INFO  c.d.s.b.FetcherBolt - [Fetcher #20] Fetched http://www.haberturk.com.tr with status 302 in msec 40
11472 [FetcherThread] INFO  c.d.s.b.FetcherBolt - [Fetcher #20] Fetched http://www.haberturk.com.tr with status 302 in msec 39
11497 [Thread-79-spout-executor[37 37]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.737+0300
11497 [Thread-57-spout-executor[31 31]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.737+0300
11497 [Thread-45-spout-executor[38 38]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.737+0300
11497 [Thread-37-spout-executor[35 35]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.737+0300
11498 [Thread-85-spout-executor[36 36]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.738+0300
11502 [Thread-29-spout-executor[33 33]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.742+0300
11502 [Thread-21-spout-executor[32 32]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.742+0300
11502 [Thread-73-spout-executor[29 29]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.742+0300
11502 [Thread-89-spout-executor[34 34]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.742+0300
11502 [Thread-51-spout-executor[30 30]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.742+0300
11517 [FetcherThread] INFO  c.d.s.b.FetcherBolt - [Fetcher #20] Fetched http://www.haberturk.com.tr with status 302 in msec 51
11524 [FetcherThread] INFO  c.d.s.b.FetcherBolt - [Fetcher #20] Fetched http://www.haberturk.com.tr with status 302 in msec 51
11563 [Thread-37-spout-executor[35 35]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 1 hits in 65 msec
11565 [Thread-51-spout-executor[30 30]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 1 hits in 62 msec
11565 [Thread-85-spout-executor[36 36]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 1 hits in 66 msec
11565 [Thread-45-spout-executor[38 38]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 1 hits in 68 msec
11565 [Thread-89-spout-executor[34 34]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 1 hits in 63 msec
11565 [Thread-79-spout-executor[37 37]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 1 hits in 68 msec
11565 [Thread-57-spout-executor[31 31]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 1 hits in 68 msec
11565 [Thread-21-spout-executor[32 32]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 1 hits in 63 msec
11567 [Thread-29-spout-executor[33 33]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 1 hits in 65 msec
11567 [Thread-73-spout-executor[29 29]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 1 hits in 65 msec
11580 [FetcherThread] INFO  c.d.s.b.FetcherBolt - [Fetcher #20] Fetched http://www.haberturk.com.tr with status 302 in msec 62
11587 [FetcherThread] INFO  c.d.s.b.FetcherBolt - [Fetcher #20] Fetched http://www.haberturk.com.tr with status 302 in msec 61
11633 [FetcherThread] INFO  c.d.s.b.FetcherBolt - [Fetcher #20] Fetched http://www.haberturk.com.tr with status 302 in msec 52
11642 [FetcherThread] INFO  c.d.s.b.FetcherBolt - [Fetcher #20] Fetched http://www.haberturk.com.tr with status 302 in msec 55
12488 [elasticsearch[Madcap][listener][T#1]] WARN  c.d.s.e.p.StatusUpdaterBolt - Could not find unacked tuple for 5443acfb013beaaa0fd654216e058ed3a0223ce65c13825ac7685ce068c71a9e
12488 [elasticsearch[Madcap][listener][T#1]] WARN  c.d.s.e.p.StatusUpdaterBolt - Could not find unacked tuple for 5443acfb013beaaa0fd654216e058ed3a0223ce65c13825ac7685ce068c71a9e
12491 [elasticsearch[Madcap][listener][T#1]] WARN  c.d.s.e.p.StatusUpdaterBolt - Could not find unacked tuple for 5443acfb013beaaa0fd654216e058ed3a0223ce65c13825ac7685ce068c71a9e
12491 [elasticsearch[Madcap][listener][T#1]] WARN  c.d.s.e.p.StatusUpdaterBolt - Could not find unacked tuple for 5443acfb013beaaa0fd654216e058ed3a0223ce65c13825ac7685ce068c71a9e
12491 [elasticsearch[Madcap][listener][T#1]] WARN  c.d.s.e.p.StatusUpdaterBolt - Could not find unacked tuple for 5443acfb013beaaa0fd654216e058ed3a0223ce65c13825ac7685ce068c71a9e
12491 [elasticsearch[Madcap][listener][T#1]] WARN  c.d.s.e.p.StatusUpdaterBolt - Could not find unacked tuple for 5443acfb013beaaa0fd654216e058ed3a0223ce65c13825ac7685ce068c71a9e
12491 [elasticsearch[Madcap][listener][T#1]] WARN  c.d.s.e.p.StatusUpdaterBolt - Could not find unacked tuple for 5443acfb013beaaa0fd654216e058ed3a0223ce65c13825ac7685ce068c71a9e
12491 [elasticsearch[Madcap][listener][T#1]] WARN  c.d.s.e.p.StatusUpdaterBolt - Could not find unacked tuple for 5443acfb013beaaa0fd654216e058ed3a0223ce65c13825ac7685ce068c71a9e
12491 [elasticsearch[Madcap][listener][T#1]] WARN  c.d.s.e.p.StatusUpdaterBolt - Could not find unacked tuple for 5443acfb013beaaa0fd654216e058ed3a0223ce65c13825ac7685ce068c71a9e
12491 [elasticsearch[Madcap][listener][T#1]] INFO  c.d.s.e.p.StatusUpdaterBolt - Bulk response 10, waitAck 0, acked 10
13499 [Thread-57-spout-executor[31 31]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.737+0300
13499 [Thread-37-spout-executor[35 35]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.737+0300
13502 [Thread-85-spout-executor[36 36]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.738+0300
13502 [Thread-21-spout-executor[32 32]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.742+0300
13502 [Thread-79-spout-executor[37 37]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.737+0300
13508 [Thread-45-spout-executor[38 38]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.737+0300
13508 [Thread-51-spout-executor[30 30]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.742+0300
13508 [Thread-73-spout-executor[29 29]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.742+0300
13508 [Thread-89-spout-executor[34 34]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.742+0300
13513 [Thread-29-spout-executor[33 33]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:26.742+0300
13536 [Thread-37-spout-executor[35 35]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 0 hits in 37 msec
13536 [Thread-57-spout-executor[31 31]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 0 hits in 37 msec
13538 [Thread-79-spout-executor[37 37]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 0 hits in 36 msec
13538 [Thread-85-spout-executor[36 36]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 0 hits in 36 msec
13539 [Thread-21-spout-executor[32 32]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 0 hits in 37 msec
13549 [Thread-51-spout-executor[30 30]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 0 hits in 41 msec
13549 [Thread-73-spout-executor[29 29]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 0 hits in 41 msec
13550 [Thread-45-spout-executor[38 38]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 0 hits in 42 msec
13552 [Thread-89-spout-executor[34 34]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 0 hits in 44 msec
13554 [Thread-29-spout-executor[33 33]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 0 hits in 41 msec
15500 [Thread-57-spout-executor[31 31]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:30.739+0300
15500 [Thread-37-spout-executor[35 35]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:30.739+0300
15502 [Thread-21-spout-executor[32 32]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:30.742+0300
15512 [Thread-51-spout-executor[30 30]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:30.752+0300
15512 [Thread-45-spout-executor[38 38]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:30.752+0300
15512 [Thread-85-spout-executor[36 36]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:30.752+0300
15512 [Thread-89-spout-executor[34 34]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:30.752+0300
15512 [Thread-79-spout-executor[37 37]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:30.752+0300
15514 [Thread-73-spout-executor[29 29]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:30.754+0300
15524 [Thread-29-spout-executor[33 33]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2017-01-06T19:40:30.764+0300
15583 [Thread-57-spout-executor[31 31]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 0 hits in 83 msec
15583 [Thread-37-spout-executor[35 35]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 0 hits in 83 msec
15584 [Thread-21-spout-executor[32 32]] INFO  c.d.s.e.p.ElasticSearchSpout - ES query returned 0 hits in 82 msec

**Comment by jnioche** [comment]
Looks like you are not sharding per host or domain. As a result all the spout instances run the same query to ES.

Check your url filters, it could be that you are preventing redirections across domains : _haberturk.com.tr_ is not the same domain as _haberturk.com_

BTW I'll be running a workshop next month in Berlin [https://twitter.com/digitalpebble/status/816398939368919040] and will cover the basics of SC

**Comment by MyraBaba** [comment]
I will check and let you know.

I will be travelling also next month may be I can find a window to visit Berlin.

**Comment by MyraBaba** [comment]
I tested for max_depth=1 and max_depth=0  for different domain

:

http://www.hurriyet.com.tr/deniz-baykal-halkin-haberi-yok-40331335	max_depth=1
http://www.haberturk.com/gundem/haber/1346487-omer-halisdemirin-babasindan-fethi-sekinin-ailesine-ziyaret	max_depth=0

:


You know the elasticsearch adress login information.  When I checked the status=FETCHED  it looks very hight to me..  

max_depth = 1 should only follow 1 link further right ?  and max_depth = 0  for the only the given url. (Such as I have 10.000 link and only want to crawl that link no follow.)

Let me know after you checked elastic search..

ie: per url  regex could be helpful 

thx

**Comment by jnioche** [comment]
> Let me know after you checked elastic search..

not clear what your question is + you would learn a bit about StormCrawler and Elasticsearch by investigating things by yourself. 

why are you putting an _ and not a . for the metadata name?

**Comment by MyraBaba** [comment]
Sorry it is my mistake. All is fine now.

**Comment by hatemalimam** [comment]
How about a set of regex per seed ?
for example I would like to fetch from bbc.com where domain contains for example sport/football,
whereas from edition.ccn.com everything with sport/golf in the URL... can I pass a set of regex to be tested against a seed ?

**Comment by jnioche** [comment]
This has not been implemented yet, so everything's possible. Do you know you can use the existing file-based regex url filter to have as many patterns as you like?

**Comment by hatemalimam** [comment]
After reading the source code I managed to implement my own seeds regex url filter, it's basically a key (domain) value (list of rules) based map. it's working fine, and each domain has its own regex file txt. it would be nice to have such feature implemented here.

Thanks for the reply.

**Comment by jnioche** [comment]
Well, all contributions are always welcome and encouraged! Feel free to open a PR if you can.

**Comment by noerw** [comment]
I would be interested in the RegEx filter per URL as well (I have a URL specific domain white- / blacklist in mind). I could possibly provide an implementation, but I would need to get familiar with the codebase first.

Also: I tried to use `metadata.max.depth` to `3` for each URL, and noticed that Metadata only seems to accept Strings and Lists of Strings. So this option only works if the value is passed as String (`"3"`).
Is that intended? It seems rather counter intuitive.

**Comment by jnioche** [comment]
Hi @noerw, thanks for your feedback. Why would you like to pass the url filters via the seed's metadata when you can use the existing URL filter implementations? Setting the rules in the metadata means that you can't modify them afterwards (or it would be very difficult) and you'd be making the status index a lot heavier. With the existing implementation, you can at least rebuild the jar and restart the topology.
What I might implement instead is a new implementation of the URL filter based on a JSON file and organised per hostname or domain, with #569 we'll even be able to refresh the resources from ES without restarting the topology.

> Also: I tried to use metadata.max.depth (set to 3 for each URL), and noticed that Metadata only seems to accept Strings and Lists of Strings. So this option only works if the value is passed as String ("3").

Not clear what you mean. Either you set the max depth in the config of the MaxDepthFilter which will take an int and will work for all the seeds, or you specify it in the seeds file as key value and you should not need an quotes

**Comment by jnioche** [comment]
see #578

**Comment by noerw** [comment]
Thanks for the quick reply!
> Not clear what you mean. Either you set the max depth in the config of the MaxDepthFilter which will take an int and will work for all the seeds, or you specify it in the seeds file as key value and you should not need an quotes

I don't have a seeds file, but get my seed URLs from Elasticsearch, where they are [inserted with custom metadata](https://github.com/52North/ecmwf-dataset-crawl/blob/master/controller/src/elastic/controllers/crawls.ts#L65-L77). Inserting `max.depth` as String works fine, while integers throw:
```js
Caused by: java.lang.ClassCastException: java.base/java.lang.Integer cannot be cast to java.base/java.util.List
        at com.digitalpebble.stormcrawler.elasticsearch.persistence.AbstractSpout.fromKeyValues(AbstractSpout.java:374) ~[crawler-alpha.jar:?]
        at com.digitalpebble.stormcrawler.elasticsearch.persistence.AggregationSpout.onResponse(AggregationSpout.java:247) ~[crawler-alpha.jar:?]
        at com.digitalpebble.stormcrawler.elasticsearch.persistence.AggregationSpout.onResponse(AggregationSpout.java:71) [crawler-alpha.jar:?]
        at org.elasticsearch.client.RestHighLevelClient$1.onSuccess(RestHighLevelClient.java:546) [crawler-alpha.jar:?]

```

**Comment by jnioche** [comment]
OK, thanks for the explanation about the depth as integer. Metadata in SC are <String,String[]> and the mapping in ES reflects that. If all your seeds use the same max depth, it would make sense to simply configure the MaxDepthFilter.

Closing the issue as we won't implement the mechanism suggested
