### ISSUE TITLE
Limit fetch to seed list

### ISSUE THREAD

**Issue by Laurent-Hervaud** [DigitalPebble/storm-crawler#400]
I not found good way to limit my crawl to my seed list :
 - in MaxDepthFilter "maxDepth": 0 not working (0 value same as empty, better -1 ?)
 - in HostURLFilter, nothing for ignoreInsideHost (inlinks)

I found a trick with RegexURLFilter : 
\# ignore all
-.

**Comment by jnioche** [comment]
Hi @Laurent-Hervaud, thanks for your comments

`parser.emitOutlinks: false` does exactly that for the JSoupParserBolt, as for the redirections you can prevent them with `redirections.allowed: false`

What you are trying to achieve can also be done by the topology itself i.e. disconnecting all inputs on the status streams going to the status updater bolt (assuming you are using one).

I take your point about maxdepth filter - it should use -1 and treat 0 as a no follow. Feel free to open a new issue for this.

Thanks

**Comment by jnioche** [comment]
Closing for now, feel free to reopen it

**Comment by jnioche** [comment]
@Laurent-Hervaud, I have implemented your suggestion for the handling of 0 in maxdepth filter. See [f46b1ab], this should deal with both outlinks and redirs. Could you please give it a try (and also confirm that the solution I gave yesterday also works)?

**Comment by Laurent-Hervaud** [comment]
Hi @jnioche 
It's not working is masdept > -1. It's like metadata.track.depth was false ? No depth in ES status index
I think there is problem in /util/MetadataTransfer.java line 162.

It's ok for the solution with parser.emitOutlinks: false

**Comment by jnioche** [comment]
Thanks @Laurent-Hervaud 

I've fixed a bug in [8bbc551] and added a test class. Would you mind giving it another try? Thanks

**Comment by Laurent-Hervaud** [comment]
I confirm that's all is working (maxdept -1;0;1)
Good job @jnioche !
