### ISSUE TITLE
Reinitialize depth to 1 when changing host or domain

### ISSUE THREAD

**Issue by Laurent-Hervaud** [DigitalPebble/storm-crawler#402]
It wood be a good improvement the possibility to have a parameter for reinitalize the depth metadata when the outlink change host or domain.
In this case we can control depth by host or domain and not only from the seed list.

**Comment by jnioche** [comment]
You could extend [MetadataTransfer](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/stormcrawler/util/MetadataTransfer.java) for that. There would probably be subtleties to add, like checking whether the target URL correspond to the root of the hostname. It depends on the particular logic of your crawl. Don't think this should be part of the core code though, again, this should be easy to achieve as-is.
