### ISSUE TITLE
Project reorganization

### ISSUE THREAD

**Issue by jakekdodd** [DigitalPebble/storm-crawler#41]
Given our discussion in #24, and previous discussions on Kafka spouts, HBase indexing, etc, we should think about reorganizing the project so that we have a core SDK and external SDK(s). 

I was thinking something like

**root**
&nbsp;&nbsp;&nbsp;&nbsp; `pom.xml`
&nbsp;&nbsp;&nbsp;&nbsp;|-> **crawler-core**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`pom.xml`
&nbsp;&nbsp;&nbsp;&nbsp;|-> **crawler-external**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`pom.xml`

The external sub-project would include things that depend on external technologies and libraries.

**Comment by jnioche** [comment]
@DigitalPebble/committers-crawler shall we proceed with this and then release 0.4? Anything else we'd want to put in the release?

**Comment by GuiForget** [comment]
I'm ok with it. The other option is to make 0.5 be just this change + the merge of metadata.

**Comment by jakekdodd** [comment]
Let's do it--working on the reorganization now.

**Comment by jakekdodd** [comment]
Take a look at 780a82c4f3ba6c3f94a61987a7803fa02bdb4c8c and let me know what you think. Clean/compile/test/package all seem to be functioning normally.

Only difference from discussion above is that the submodule artifacts are named 'sc-core' and 'sc-external,' so that we don't have to change the parent project name from 'storm-crawler.' Directories are named 'core' and 'external,' though.

**Comment by GuiForget** [comment]
My early feedback:
- Regarding the artifact names, I assumed sc-core was just to keep it short during the discussion but I see that's the actual name you use. I'd prefer the full name storm-crawler-core
- Exec maven plugin. There's a version 1.3.x now
- in sc-external, I don't think the exec plugin is required
- in sc-external, I don't think you want the test-jar. 
- in both projects, do we still need the big jar? Shouldn't this be done solely in spiderling?

**Comment by jakekdodd** [comment]
Agree on all points there. For consistency, should we also change sc-external to storm-crawler-external?

**Comment by GuiForget** [comment]
Yes, that was implied :)

**Comment by jakekdodd** [comment]
Should probably add this as a separate issue, but it looks like the javadoc goal still breaks the release profile. @GuiForget I remember you brought this up a while ago...did we have any intended resolution on that?

**Comment by GuiForget** [comment]
The resolution was that it worked for @jnioche  :)

**Comment by jnioche** [comment]
+1 to Gui's points above

* bigjar : can explain in Wiki how to do that and it is in Spiderling indeed but I quite liked being able to run in distributed Storm just by tweaking  the CrawlTopology in core.

* should not we move the dependencies from the parent pom to core? 

* will need rebasing to incorporate most recent changes to master?

* I'd move the whole of the metrics package to external as well as the Codahale dependency. The only change it would require would be to remove 

```
import com.digitalpebble.storm.metrics.HistogramMetric;
import com.digitalpebble.storm.metrics.MeterMetric;
import com.digitalpebble.storm.metrics.TimerMetric;
```

from the ParserBolt and rely on the standard `backtype.storm.metric` implementations. The rest of the code in core does not rely on what we have in the metrics package which I think is a good thing. I will open a new issue for refactoring the metrics in ParserBolt.

* Javadoc and release : see #27

**Comment by jnioche** [comment]
Metrics package \: of course it is not external in the sense that it relies on a third party library (although it does with Codahale) but it is external in the sense that it is a non-core component the use of which is completely optional. Longer term we'll see what happens to it and whether it makes sense to keep it or not.

**Comment by jakekdodd** [comment]
> bigjar : can explain in Wiki how to do that and it is in Spiderling indeed but I quite liked being able to run in distributed Storm just by tweaking the CrawlTopology in core.

Good point, the bigjar for sc-core might have some usefulness in development. Let's leave it in the sc-core pom for now...if it's not being used, we can easily remove it in the future.

> should not we move the dependencies from the parent pom to core?

Yeah the original intent was to keep them in the parent pom so that we could selectively exclude them from child projects. But, for now it seems unlikely that we'll have any child projects of sc-core, so I'll move the deps there.

> Javadoc and release : see #27

In my development environment, running `mvn package -P release` produces a ton of Javadoc-related complaints. @jnioche does that command successfully execute for you?

**Comment by jnioche** [comment]
Only getting \:
```
2 warnings
[WARNING] Javadoc Warnings
[WARNING] /data/storm-crawler/src/main/java/com/digitalpebble/storm/crawler/filtering/URLFilterUtil.java:45: warning - @param argument "configuration" is not a parameter name.
[WARNING] /data/storm-crawler/src/main/java/com/digitalpebble/storm/crawler/filtering/URLFilterUtil.java:64: warning - @param argument "target" is not a parameter name.
[INFO] Building jar: /data/storm-crawler/target/storm-crawler-0.4-SNAPSHOT-javadoc.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.447s
[INFO] Finished at: Mon Jan 19 12:37:08 GMT 2015
[INFO] Final Memory: 21M/222M
[INFO] ------------------------------------------------------------------------
```

**Comment by jakekdodd** [comment]
New commit b33c073e749792d505cd994261643aef28e4dbbb:

* Test-jar not produced for sc-external with the release profile
* Renamed submodules to storm-crawler-core and storm-crawler-external (will continue to refer to these with the 'sc' prefix in discussions for brevity)
* Bigjar is again included in the sc-core pom
* Added dependencyManagement and pluginManagement sections in the parent pom for reused dependencies; jackson-databind has been included anticipating that we'll have classes in sc-external that use the JSON-driven plugin system.

I avoided refactoring the metrics for now until the metrics in ParserBolt have been refactored. Once that's done, we can move the codehale and librato stuff into sc-external

**Comment by jnioche** [comment]
> I avoided refactoring the metrics for now until the metrics in ParserBolt have been refactored. Once that's done, we can move the codehale and librato stuff into sc-external

This has been done see #65 

Will check your latest commit on Wednesday.

**Comment by jakekdodd** [comment]
Have rebased against master, with #65 applied the metrics are now located in `com.digitalpebble.storm.crawler.codehale.metrics.*` and `com.digitalpebble.storm.crawler.librato.metrics.*` packages

**Comment by jnioche** [comment]
[https://github.com/DigitalPebble/storm-crawler/tree/project-reorganization/core/src/main/java/com/digitalpebble/storm/metrics] package still appears in core. 

I'd leave the codehale related stuff under `com.digitalpebble.storm.crawler.metrics` as the fact that they leverage codehale is not very important from a functional point of view, whereas the librato related code could be in com.digitalpebble.storm.crawler.metrics.librato.* maybe?

**Comment by jakekdodd** [comment]
> package still appears in core.

Haven't made and pushed the commit yet, wanted to finish the discussion first so we don't have a bunch of random commits in the history

Regarding:
> I'd leave the codehale related stuff under com.digitalpebble.storm.crawler.metrics

and 

> com.digitalpebble.storm.crawler.metrics.librato.*

That seems more sensible and less verbose to me; the reason why I named the packages `com.digitalpebble.storm.crawler.<dependency name>.metrics.*` was for consistency (mirroring `com.digitalpebble.storm.crawler.elasticsearch.*`). This came from the discussion above where we decided it would be better to organize the packages by dependency, rather than by component.

Still, those package names seem like a mouthful to me. What do you think?

**Comment by jnioche** [comment]
> it would be better to organize the packages by dependency, rather than by component

I agree but I think it is a bit different for the metrics as the dependency does not really matter. Later on we'll have the same sort of components (spout, status updater bolt, indexers, etc...) for different backends (ES, SOLR, HBase) and that's where it will make sense to organise per dependency.

 > Still, those package names seem like a mouthful to me.

I am not too bothered about that. Do you have any alternatives in mind?

**Comment by jakekdodd** [comment]
Newest commit is cb47e58769bc73435434220ed2988e0e18d49d71

* Codehale-related stuff is in `com.digitalpebble.storm.crawler.metrics.*`
* Librato-related stuff is in `com.digitalpebble.storm.crawler.librato.metrics*`. This is similar to your suggested `com.digitalpebble.storm.crawler.metrics.librato.*`, but will help with consistency if/when we eventually have Elasticsearch/Logstash/Redis/etc. metrics consumers, which would then be organized under their respective dependency packages.

**Comment by jnioche** [comment]
Both core and external's poms contain \:

```
    <dependency>
      <groupId>org.apache.storm</groupId>
      <artifactId>storm-core</artifactId>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
    </dependency>
```

is that necessary given that it is already in the parent pom? Shouldn't they be scoped as `provided` and `test` respectively?

`jackson-databind` is in both the parent and the core pom.

the README will probably need changing to add 'core' in the paths where needed.

**Comment by jakekdodd** [comment]
Yep, when using dependencyManagement, you still need to explicitly state in the child pom that you're using a declared dependency. They inherit the scope from that declared in the parent pom (see documentation [here](http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management)).

The `jackson-databind` dependency will probably be used at some point or another by external components, so it's in the parent pom but not declared in `sc-external` until it's actually used

**Comment by jnioche** [comment]
@jakekdodd thanks for the explanation

**Comment by jnioche** [comment]
Done in #70
