### ISSUE TITLE
Improve charset detection

### ISSUE THREAD

**Issue by lukb** [DigitalPebble/storm-crawler#438]
Charset detection works fine in most cases, but looking at the cases when it fails makes me think how it can be improved.

I found this page useful for a general guidance:
https://www.w3.org/International/questions/qa-html-encoding-declarations

In short, here's the detection sequence based on the above resource:

1) Look for BOM ("byte-order mark", hex: EF BB BF) at the beginning of the content. If present, assume UTF-8. 
2) If BOM is not found in (1), look for charset declaration in HTTP Content-Type Header.
3) If declared charset not found in (2), take a look at meta tags (two cases to consider: <meta charset... and <meta content...)

If charset is not found after those 3 checks what's probably sensible is to entirely depend on a text-based charset detection.

Here's the charset detection bit I found in storm-crawler in JSoupParserBolt:

```
private String getContentCharset(byte[] content, Metadata metadata) {
        String charset = null;

        // check if the server specified a charset
        String specifiedContentType = metadata
                .getFirstValue(HttpHeaders.CONTENT_TYPE);
        try {
            if (specifiedContentType != null) {
                ContentType parsedContentType = ContentType
                        .parse(specifiedContentType);
                charset = parsedContentType.getCharset().name();
                if (maxLengthCharsetDetection == 0) {
                    return charset;
                }
            }
        } catch (Exception e) {
            charset = null;
        }

        // filter HTML tags
        charsetDetector.enableInputFilter(true);
        // give it a hint
        charsetDetector.setDeclaredEncoding(charset);
        // trim the content of the text for the detection
        byte[] subContent = content;
        if (maxLengthCharsetDetection != -1
                && content.length > maxLengthCharsetDetection) {
            subContent = Arrays.copyOfRange(content, 0,
                    maxLengthCharsetDetection);
        }
        charsetDetector.setText(subContent);
        try {
            CharsetMatch charsetMatch = charsetDetector.detect();
            if (charsetMatch != null) {
                charset = charsetMatch.getName();
            }
        } catch (Exception e) {
            // ignore and leave the charset as-is
        }
        return charset;
    }
```

CharsetDetector and CharsetMatch come from ICU4J http://site.icu-project.org/

From my understanding the code above looks for charset declared in Content-Type Header and if found uses it as a hint in further detection via CharsetDetector (as long as the maxLengthCharsetDetection is not set to 0). 

What's worth pointing out here is that CharsetDetector.detect() will take precedence over the declared charset in the HTTP Header if present. 
Also, I couldn't find any sign of parsing meta tags in order to determine charset declaration (let me know if it's there somewhere). 

So how can charset detection be improved? Take a hint from meta tags like for example here:
https://github.com/apache/tika/blob/9130bbc1fa6d69419b2ad294917260d6b1cced08/tika-parsers/src/main/java/org/apache/tika/parser/html/HtmlEncodingDetector.java

But I wonder, is it such a common case to find the declared charset to be different from the actual content encoding and that is why the current charset detection implementation relies on the dynamic detection via CharsetDetector to have a final say?

Looking at source code of CharsetDetector reveals that in fact detect() method returns only the first matching charset of all charsets that are a possible match (the array is suppose to be ordered by highest probability descending). CharsetDetector.detectAll() returns all the matching charsets. 

I have seen CharsetDetector.detect() wrongly returning ISO-8859-1 despite hinted ISO-8859-2 via         charsetDetector.setDeclaredEncoding() which came from HTTP header value (I wish I had an actual example at hand), so I'm not too sure how reliable it is.

What do you think about changing the charset detection implementation to resort to CharsetDetector only if HTTP/HTML-level charset declaration was not found? To factor in one more aspect: skipping CharsetDetector.detect() in some cases would yield performance benefits.

After all, I think it comes down to a question who is wrong more often on average: hinted CharsetDetector.detect() or HTTP/HTML-level charset declaration found in the crawled websites.

**Comment by jnioche** [comment]
Thanks @lukb 

> What do you think about changing the charset detection implementation to resort to CharsetDetector only if HTTP/HTML-level charset declaration was not found? To factor in one more aspect: skipping CharsetDetector.detect() in some cases would yield performance benefits.

We could make it configurable at least e.g. `charset.detection.override` with a value of `true` would correspond to the current behaviour whereas `false` would do what you described. 

> After all, I think it comes down to a question who is wrong more often on average: hinted CharsetDetector.detect() or HTTP/HTML-level charset declaration found in the crawled websites.

Exactly, I thought there had been work on this based on CommonCrawl but I can't find any trace of it. @sebastian-nagel do you know anything related to this?

We could also log the cases where there is a discrepancy between the detection and what the headers contained. This would give us concrete examples for debugging.

**Comment by sebastian-nagel** [comment]
The [fix](/iipc/webarchive-commons/commit/ed33bae09360ebf57e751e28b3eae2183b62237e) was simply to use [StandardCharsetDetector](/iipc/webarchive-commons/blob/master/src/main/java/org/archive/format/text/charset/StandardCharsetDetector.java) which is based on a trivial heuristic: take the charset found first in the hierarchy of (1) HTTP header, (2) HTML meta data or (3) guessed by org.mozilla.juniversalchardet. I checked one CC WARC file for errors of this approach: it works quite well, looks like for languages where encoding is crucial the web masters know what they do. Most errors affected English texts containing apostrophes, copy right marks and occasional Spanish words.

Adding a charset from HTML meta may help, also `detect.charset.maxlength: 2048` may be too small (cf. [NUTCH-2042](https://issues.apache.org/jira/browse/NUTCH-2042)/[TIKA-357](https://issues.apache.org/jira/browse/TIKA-357)) to get textual content from the HTML body for the detector.

**Comment by jnioche** [comment]
Example of failed identification

http://www.kidstaff.com.ua/tema-11530898.html => http header and html agree on windows-1251 but identifier returns "ISO-8859-8-I" which throws an UnsupportedCharsetException.

**Comment by jnioche** [comment]
Note: the [DataUtil class in JSoup ](https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/helper/DataUtil.java#L93) uses the BOM info and if not found looks into the metatags, however if a value is passed by the user (as we do with the content type coming from the detector, the latter is used de facto).

**Comment by jnioche** [comment]
@lukb I have implemented as slightly different logic in a new branch `charset`, following Ken's suggestion in https://github.com/crawler-commons/crawler-commons/issues/171
Comments welcome as usual!

**Comment by lukb** [comment]
Looks good. 

Any reason why BOM is not the first condition to check? 

From: https://www.w3.org/International/questions/qa-html-encoding-declarations

> If you have a UTF-8 byte-order mark (BOM) at the start of your file then recent browser versions other than Internet Explorer 10 or 11 will use that to determine that the encoding of your page is UTF-8. It has a higher precedence than any other declaration, including the HTTP header.
> 
> You could skip the meta encoding declaration if you have a BOM, but we recommend that you keep it, since it helps people looking at the source code to ascertain what the encoding of the page is.

Checking BOM and skipping the rest could be a performance boost as well.

**Comment by jnioche** [comment]
@kkrugler any reasons not to trust the BOM before anything else?

**Comment by jnioche** [comment]
@lukb I decided to use BOM first as per your suggestion and will merge shortly unless someone disagrees.

**Comment by lukb** [comment]
That sounds good, Julien.
