### ISSUE TITLE
Fetature Request- Support recursive crawling in the CrawlTopology

### ISSUE THREAD

**Issue by foromer4** [DigitalPebble/storm-crawler#448]
To support  recursive crawling ,it is suggested to modify the `CrawlTopology `used by the archtype so that it uses the `MemoryUpdaterBolt`.
Also, need to pass metadata to streams as a field.

**Comment by jnioche** [comment]
Hi @foromer4 

> Also, need to pass metadata to streams as a field.

should be the case already

do you want to submit a PR for this?

Thanks!

**Comment by foromer4** [comment]
Sure ,I will take it.

**Comment by jnioche** [comment]
Closing as there has been no progress on it and it is a trivial task
