### ISSUE TITLE
Twitter HERON upgrade label:wish

### ISSUE THREAD

**Issue by MyraBaba** [DigitalPebble/storm-crawler#456]
Hi,

We loved Twitter Heron simplicity , UI and performance. 

Do you have a plan to upgrade Twitter Heron or a way to support code base for Heron ?

Best

**Comment by jnioche** [comment]
Hi @MyraBaba 

We'll see how Apache Storm and Heron evolve but at the moment this is definitely not planned.
I haven't tried Heron very much but it did not strike me as being simpler than Storm, quite the opposite. As for performance, is this something you observed yourself or have you just read about it? IIRC the comparisons I saw were based on older versions of Storm and anyway for web crawling, the bottlenecks are the politeness and the speed of the backends for recursive crawls, not much to do with Storm itself.
