### ISSUE TITLE
Installing Storm crawler on Cygwin

### ISSUE THREAD

**Issue by cadelina** [DigitalPebble/storm-crawler#461]
Is it possible to run Storm-crawler using Cygwin?

I've got Elasticsearch and Kibana installed on Windows 2012 but I can't get Storm-crawler to run under Windows. 

What I've done is install Cygwin but I cannot execute Storm within Cygwin.

Any ideas?

**Comment by jnioche** [comment]
Hi @cadelina 

http://ptgoetz.github.io/blog/2013/12/18/running-apache-storm-on-windows/ explains the steps to follow

Alternatively you could run SC without Storm and via Maven with 

`mvn clean compile exec:java -Dexec.mainClass=org.apache.storm.flux.Flux -Dexec.args="--local crawler.flux --sleep 60000"`

For questions, please use StackOverflow, thanks!
