### ISSUE TITLE
Usage of DateFormat is not thread-safe

### ISSUE THREAD

**Issue by tendres1980** [DigitalPebble/storm-crawler#490]
The usage of DateFormat in several classes is not thread-safe. Either use the new Java 8 date/time API or make them thread-safe.

e.g. for Java 8 replace
`protected SimpleDateFormat httpDateFormat = new SimpleDateFormat(
            "EEE, dd MMM yyyy HH:mm:ss zzz", Locale.US);`

with:
`protected DateTimeFormatter httpDateFormat = java.time.format.DateTimeFormatter.RFC_1123_DATE_TIME;`

then format the current time via:
`ZonedDateTime date = ZonedDateTime.now(ZoneId.systemDefault());
String now = httpDateFormat.format(date);`

For Java <8:
`private static final ThreadLocal<DateFormat> DATEFORMAT = new ThreadLocal<DateFormat>() {
        protected DateFormat initialValue() {
            return new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss zzz", Locale.US);
        }
    };`

**Comment by jnioche** [comment]
Same as for the other issue, please reopen it if you want me to look at it.
I can see only 2 uses of DateFormat - one in the ES metrics consumers and one in AbstractStatusUpdaterBolt, where it does not matter as we know that the execute method is not accessed by more than one thread at a time. Any other uses I've missed?
