### ISSUE TITLE
Status dashboard fails to visualize Top-Hosts

### ISSUE THREAD

**Issue by wolverline** [DigitalPebble/storm-crawler#494]
I followed the import process and the Kibana Json file looks like:

Line: 9
`"panelsJSON": "[{\"col\":1,\"id\":\"status-count\",\"row\":1,\"size_x\":4,\"size_y\":5,\"type\":\"visualization\"},{\"id\":\"Top-Hosts\",\"type\":\"visualization\",\"size_x\":4,\"size_y\":5,\"col\":5,\"row\":1}]",`

The screen shot:
![kibana_status](https://user-images.githubusercontent.com/460865/29577477-91576bca-8739-11e7-8f9b-ebaffc3c05c3.png)

Is this a bug or something I missed out some settings?

**Comment by jnioche** [comment]
Did you change the following [config](https://github.com/DigitalPebble/storm-crawler/blob/master/external/elasticsearch/es-conf.yaml#L27)?

  _es.status.routing.fieldname: "metadata.hostname"_

Did you load the dashboard schema before injecting the documents? If so, Kibana does not know that there is a field `metadata.hostname`. Could you try to refresh the field list in Management -> Index? 

One option would be to have a generic field name e.g. `key` regardless of what we use for sharding (host/domain/ip) and define it in the ES mapping script.

**Comment by jnioche** [comment]
Can't reproduce. Please reopen with more info if still relevant
