### ISSUE TITLE
Change URLFilter interface to optionally take metadata

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#53]
This would be useful for several use cases such as [https://github.com/PopSugar/storm-crawler-extensions/pull/2] or [https://github.com/DigitalPebble/storm-crawler/pull/46] where in both cases we need to know the source URL of a new link (or rather its domain or hostname).

This is similar to [https://github.com/DigitalPebble/storm-crawler/issues/25].

We'd then be able to enforce the filtering based on whether a URL is from the same hostname or domain as the URL it originates from as a normal URLFilter which would make the code more compact and easier to reuse from various parsing bolts or the Fetcher (e.g. redirections).

Should this be done before or after [https://github.com/DigitalPebble/storm-crawler/pull/36]?

**Comment by jnioche** [comment]
The URLs that are filtered in ParserBolt don't have metadata, the metadata are created in the subsequent stages. The URLFilters also don't get access to the config at all, but could could be configured via their bespoke JSON config files.
We could create some temporary metadata just to convey the source URL but in that case wouldn't it be simpler to just pass the source URL directly and have filter(String source, String target)?

**Comment by jnioche** [comment]
Have implemented a util class to simplify the filtering of URLs based on the host or domain name of the source URL [https://github.com/DigitalPebble/storm-crawler/commit/c6aa373965e0d8f24e84c97ef21df2c830bad31e] as a temporary solution.

**Comment by GuiForget** [comment]
I'm going to work on that so I get more familiar with this piece of the code
