### ISSUE TITLE
Contribute to Wiki

### ISSUE THREAD

**Issue by hatemalimam** [DigitalPebble/storm-crawler#532]
Hello,

Is there anyway to contribute to the wiki, I've seed a lot of outdated info, misleading in a form, or broken links like this case.

![screen shot 2018-02-20 at 15 51 39](https://user-images.githubusercontent.com/3439970/36430663-0a56943c-1656-11e8-9a1a-43514cd9e857.png)

For example this information was very critical for me: 

http.content.limit
![screen shot 2018-02-20 at 15 48 26](https://user-images.githubusercontent.com/3439970/36430474-8bdceebc-1655-11e8-9ca4-00dc887d5706.png)

But as I have seen [here](https://github.com/DigitalPebble/storm-crawler/blob/69782186fd33b26acc0156e3f712908535c3d7af/core/src/main/java/com/digitalpebble/stormcrawler/protocol/httpclient/HttpProtocol.java#L289) it's implemented, and that particular attribute prevented the whole loading of some documents due to that limit, so some XPath filters weren't working of course.

Anyway my question is is there anyway I can contribute to the Wiki ? github doesn't allow that I guess.

**Comment by jnioche** [comment]
Hi, your contribution to the wiki would be very welcome. Editing the WIKI is currently allowed to members of a group with write access, I've sent you an invitation to join and you should be able to make changes to the wiki once you've accepted it. Keeping the WIKI and other documentation in sync with changes in the code is always a challenge.

**Comment by hatemalimam** [comment]
Thanks, I've accepted it. I'll make sure to have some valuable contribution.
