### ISSUE TITLE
http.content.limit inconsistent defaults

### ISSUE THREAD

**Issue by hatemalimam** [DigitalPebble/storm-crawler#533]
The default value for `http.content.limit` in [`crawler-default.yaml`](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/resources/crawler-default.yaml#L47) is `65536`

Whereas in the http protocols is `-1` in case it's not present in the config
https://github.com/DigitalPebble/storm-crawler/blob/69782186fd33b26acc0156e3f712908535c3d7af/core/src/main/java/com/digitalpebble/stormcrawler/protocol/httpclient/HttpProtocol.java#L99

IMHO we should have that `-1` as a default, any reason to have a limit as a default ?

In my case some of the content was not fetched due to that limit.

If it's for some reason a bad idea, then I guess the default value in the http protocols should be `65536`.

**Comment by jnioche** [comment]
Having a limit on the size is just to keep large, generic crawls efficient against fetching continuous streams e.g. radio, tv. It could be set to a larger value to accommodate larger files like sitemaps or unlimited with -1. I suppose it would be less confusing to have the same value in the default config and in the code as someone looking at the code wouldn't know what is being used. 
A good compromise would be to have -1 in the code as well as the default config but use the limited value in [the conf generated by the archetype](https://github.com/DigitalPebble/storm-crawler/blob/master/archetype/src/main/resources/archetype-resources/crawler-conf.yaml) - that would be more visible to the users. What do you think @hatemalimam?

**Comment by hatemalimam** [comment]
Absolutely, the idea of the generated conf by the archetype would be very clear to the user. I would go with that. I can open a pull request if you want for this tiny mod.

**Comment by jnioche** [comment]
yes please!
