### ISSUE TITLE
FeedParserBolt: metadata added by parse filters not passed forward in topology

### ISSUE THREAD

**Issue by sebastian-nagel** [DigitalPebble/storm-crawler#541]
FeedParserBolt does not pass the metadata add by parse filters forward in the topology. AdaptiveFetchSchedule does not recognize anymore whether a feed has change by signature comparison ([cc/news-crawl#19](/commoncrawl/news-crawl/issues/19)). [f344f4b](/DigitalPebble/storm-crawler/commit/f344f4b5806a24d8f2e1116054ba0abce6a365e8#diff-f44921216e56b5182698d433c5d4ee70R137) has changed the way metadata is passed to the parsefilters in FeedParserBolt and SiteMapParserBolt while tika and jsoup parsers still work on the Metadata object directly (set by `parseData.setMetadata(metadata)`)

**Comment by jnioche** [comment]
thanks @sebastian-nagel. the shortcut `parse.put(url, metadata)` creates a new instance of metadata under the bonnet and copies the values from the original metadata which indeed causes a problem aswe use and return the latter further down the code. Will fix this now.

**Comment by sebastian-nagel** [comment]
Thanks, @jnioche!
