### ISSUE TITLE
Purge internal queues of tuples which have already reached time out 

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#564]
URLs can sit in the internal queues of the FetcherBolt longer than the value set in _topology.message.timeout.secs_. This happens for instance when there aren't enough fetching threads or if the server corresponding to the queue is slow. By the time the URL gets fetched, its tuple will have been failed by Storm. Even with ES, where _es.status.ttl.purgatory_ allows a delay until an acked or failed URL is allowed through the topology, we can have the same URL reentering the queues later on. We could deduplicate the URLs in the queues but it is probably better and simpler to simply purge them if they have gone over the timeout. The following URLs will also to have less time to wait.

**Comment by sebastian-nagel** [comment]
+1

_es.status.ttl.purgatory_ must be set close to `fetcher.max.crawl.delay * fetcher.max.queue.size` to reliably avoid duplicate fetches for sites which request slow crawling. That's usually a large time span (eg. 20 min.), sounds good if this can be set to a lower value.
