### ISSUE TITLE
Caching of redirected robots.txt may overwrite correct robots.txt rules

### ISSUE THREAD

**Issue by sebastian-nagel** [DigitalPebble/storm-crawler#573]
Redirected robots.txt rules should be only cached for the target host if the URL path is `/robots.txt` otherwise the redirect may overwrite the correct robots rules, see [NUTCH-2581](https://issues.apache.org/jira/browse/NUTCH-2581).

**Comment by jnioche** [comment]
In the example you gave in NUTCH-2581, the target URL ends in /robots.txt  so I'm not sure I understand the problem.

**Comment by sebastian-nagel** [comment]
It must be exactly `/robots.txt`, not `/wyomingtheband/robots.txt` or anything else. The problem is that the [current logic](/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/stormcrawler/protocol/HttpRobotRulesParser.java#L167) assumes that the content returned for https://www.facebook.com/wyomingtheband/robots.txt is equivalent to that of https://www.facebook.com/robots.txt which is definitely not the case. Regarding the example: this redirect and [many more](http://index.commoncrawl.org/CC-MAIN-2018-17-index?url=facebook.com&matchType=domain&output=json&filter=~url:.*/robots\.txt) mask the correct robots.txt and cause that even frequently the host www.facebook.com is considered to be allowed for crawling. Of course, there is some random what is fetched and cached first.

**Comment by jnioche** [comment]
Ok, got it, thanks Sebastian. Will fix it right now.

**Comment by sebastian-nagel** [comment]
Thanks, @jnioche!
