### ISSUE TITLE
Allow for the setting of Status enum from the config file.

### ISSUE THREAD

**Issue by danielamaya** [DigitalPebble/storm-crawler#574]
It would be nice to be able to configure the Status enum from the config file. This would allow the user to define what status codes are considered FETCH, FETCH_ERRORS, etc. Something along the lines of the example below.

```
http.status.code.FETCH_ERROR:
- 750
- 790
```

**Comment by jnioche** [comment]
Thanks @danielamaya. For that specific example, the [fromHTTPCode method](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/stormcrawler/persistence/Status.java#L33) returns FETCH_ERROR for any value which is not a SUCCESS or REDIRECTION. Adding the config as suggested would not change the behaviour at all.
Can you give me an example of a case where the codes for FETCHED (300 / 204) or REDIR (3xx) should be different from what we currently handle? 
We could set these mappings in the default configuration and let users override them if necessary. The fromHTTPCode method is called from [only a few places](https://github.com/DigitalPebble/storm-crawler/search?q=fromHTTPCode&unscoped_q=fromHTTPCode) and the change would not be huge but I'd like to make sure that there are good reasons for doing it first.

**Comment by danielamaya** [comment]
Actually, my only example would be for FETCH_ERROR. The logic for everything else is fine for me.  Reading the documentation for statusStream, I see the following:

> The difference between FETCH_ERROR and ERROR is that the former is possibly transient whereas the latter is terminal.

I understand that 404 could indicate a server under stress, meaning a 404 could potentially be considered a transient error. However, in my case a 404 is terminal, whereas a 606 is a custom code used by the server meaning I've been rate limited. Looking at the logic of the [Status enum](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/stormcrawler/persistence/Status.java) it seems that anything above a 400 will be considered a FETCH_ERROR, meaning a 404 would be considered a FETCH_ERROR. I'd like to be able to configure what is considered terminal (i.e., don't attempt to fetch again), and what codes are actually considered FETCH_ERROR (i.e., retry after time specified by fetchInterval.fetch.error).

**Comment by jnioche** [comment]
Closing for now @danielamaya, feel free to comment on the solution I suggested
