### ISSUE TITLE
NPE in elasticsearch CollapsingSpout

### ISSUE THREAD

**Issue by noerw** [DigitalPebble/storm-crawler#595]
`com.digitalpebble.stormcrawler.elasticsearch.persistence.CollapsingSpout` throws a NPE due to `lastDate` being `null`:

https://github.com/DigitalPebble/storm-crawler/blob/1.10/external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/CollapsingSpout.java#L187

To reproduce, just configure an empty or nonexistent status index.

v1.9 is also affected. `AggregationSpout` might be affected as well.

**Comment by jnioche** [comment]
It happens with an empty status index. If the index does not exist at all we get 

`org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=index_not_found_exception, reason=no such index]`

which is normal and expected. The init script must be called prior to running the topology.

The issue happens with the CollapsingSpout only, not with the AggregationSpout. I'll push a fix as soon as github is working again. Can't pull or push at the moment.

**Comment by jnioche** [comment]
here is the diff for it

```
--- a/external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/CollapsingSpout.java
+++ b/external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/CollapsingSpout.java
@@ -169,18 +169,6 @@ public class CollapsingSpout extends AbstractSpout implements
         SearchHit[] hits = response.getHits().getHits();
         int numBuckets = hits.length;
 
-        // no more results?
-        if (numBuckets == 0) {
-            lastDate = null;
-            lastStartOffset = 0;
-        }
-        // still got some results but paging won't help
-        else if (numBuckets < maxBucketNum) {
-            lastStartOffset = 0;
-        } else {
-            lastStartOffset += numBuckets;
-        }
-
         // reset the value for next fetch date if the previous one is too old
         if (resetFetchDateAfterNSecs != -1) {
             Calendar diffCal = Calendar.getInstance();
@@ -237,6 +225,18 @@ public class CollapsingSpout extends AbstractSpout implements
                 "{} ES query returned {} hits from {} buckets in {} msec with {} already being processed",
                 logIdprefix, numDocs, numBuckets, timeTaken, alreadyprocessed);
 
+        // no more results?
+        if (numBuckets == 0) {
+            lastDate = null;
+            lastStartOffset = 0;
+        }
+        // still got some results but paging won't help
+        else if (numBuckets < maxBucketNum) {
+            lastStartOffset = 0;
+        } else {
+            lastStartOffset += numBuckets;
+        }
+
         // remove lock
         isInESQuery.set(false);
     }

```

**Comment by jnioche** [comment]
thanks for reporting it @noerw 
please give the master branch a try

**Comment by noerw** [comment]
Thanks for the fix!
I used a wildcard for the status index `crawlstatus-*`, and in that case there is no `index_not_found_exception` when there is no match, but a valid response with no hits (ES 6.2).

**Comment by jcruzmartini** [comment]
Hi @jnioche , we have been dealing with something similar those days in our project, is same scenario because we are using also status* as @noerw is using, when we do not have any status index created yet we are getting an exception on StatusMetricBolt.

`87152 [Thread-62-status_metrics-executor[24 24]] INFO  c.d.s.e.m.StatusMetricsBolt - Multiquery returned in 279 msec
87164 [Thread-62-status_metrics-executor[24 24]] ERROR o.a.s.util - Async loop died!
java.lang.RuntimeException: java.lang.NullPointerException
    at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:522) ~[storm-core-1.2.2.jar:1.2.2]
    at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:487) ~[storm-core-1.2.2.jar:1.2.2]
    at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:74) ~[storm-core-1.2.2.jar:1.2.2]
    at org.apache.storm.daemon.executor$fn__10795$fn__10808$fn__10861.invoke(executor.clj:861) ~[storm-core-1.2.2.jar:1.2.2]
    at org.apache.storm.util$async_loop$fn__553.invoke(util.clj:484) [storm-core-1.2.2.jar:1.2.2]
    at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
    at com.digitalpebble.stormcrawler.elasticsearch.metrics.StatusMetricsBolt.execute(StatusMetricsBolt.java:145) ~[stormcrawler-1.1.0.jar:?]
    at org.apache.storm.daemon.executor$fn__10795$tuple_action_fn__10797.invoke(executor.clj:739) ~[storm-core-1.2.2.jar:1.2.2]
    at org.apache.storm.daemon.executor$mk_task_receiver$fn__10716.invoke(executor.clj:471) ~[storm-core-1.2.2.jar:1.2.2]
    at org.apache.storm.disruptor$clojure_handler$reify__10135.onEvent(disruptor.clj:41) ~[storm-core-1.2.2.jar:1.2.2]
    at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:509) ~[storm-core-1.2.2.jar:1.2.2]
    ... 6 more`

if you want and you think that this will add some value to the project, I can create a PR for fixing that NPE that is being thrown when there is not any index created yet.

Thanks in advance

**Comment by jnioche** [comment]
Hi @jcruzmartini 
StatusMetricBolt -> yes please a PR would be welcome. I'll try to reproduce the problem
AggregationSpout-> do you have the source of the NullPointerException further down in the logs? Could you please open a separate issue for it?
Thanks

**Comment by jcruzmartini** [comment]
sure! thanks @jnioche
