### ISSUE TITLE
WARCHdfsBolt writes zero byte files

### ISSUE THREAD

**Issue by keyboardsamurai** [DigitalPebble/storm-crawler#596]
As discussed [in a stackoverflow thread](https://stackoverflow.com/questions/51654160/getting-a-topology-on-stormcrawler-to-properly-write-warc-files/51670822#51670822), I tried to create a storm-crawler-archetype 1.10 based project that emits warc files. Unfortunately though, these warc files always appear empty and contain 0 bytes. 

[I created a repo](https://github.com/keyboardsamurai/storm-test-warc) where the setup is shown. Also I tried to amend the suggestions that @jnioche gave me (Adding a FileTimeSizeRotationPolicy set to rotate every 10 seconds and 10 Kbytes and setting a new CountSyncPolicy(1)) to no avail.

The command I use to run this example is `mvn clean package && storm jar target/test-1.0-SNAPSHOT.jar test.CrawlTopology -conf ./crawler-conf.yaml -local`

**Sidenote:**
I also downgraded the test repo case from above to SC 1.8 and Storm 1.2.1 respectively [in this branch right here](https://github.com/keyboardsamurai/storm-test-warc/tree/0_8_VERSION), but couldn't get that to write a proper WARC file either when using time based rotation - these files were 4 Kilobytes in size but appeared to be invalid gzip files with some binary content. 

However, when either lowering the filesize threshold to an excessive value like 4 kbyte or using the MemoryStatusUpdater for recursion, valid single page archives started to appear. It seems that flushing behavior might still be somewhat random.

**Comment by jnioche** [comment]
Note to self: you can configure HDFS like this

```
        warcbolt.withConfigKey("warc");
        Map<String, Object> hdfsConf = new HashMap<>();
        hdfsConf.put("fs.file.impl", "org.apache.hadoop.fs.RawLocalFileSystem");
        getConf().put("warc", hdfsConf);
```

This uses the RawLocalFileSystem, which unlike the checksum one used by default does a proper sync of the content to the file. This does not mean that the content can be correctly extracted though.

**Comment by jnioche** [comment]
@sebastian-nagel have you tried the WARC module since the changes you made in https://github.com/DigitalPebble/storm-crawler/commit/0afe3ede45f9474d5684257735c3ceb93336f53a#diff-5332acd41a61ec17dd64f203a6132c33 ?

**Comment by jnioche** [comment]
Have found the cause of the problem and fixed it. This had to do with the compression of the entries. We should now get a valid gzip regardless of whether triggered by a sync or a rotation.

Thanks @keyboardsamurai for reporting it. Please give the fix a try if you can.
