### ISSUE TITLE
wish: possibility to store "HTTP status code" in the ES status index? 

### ISSUE THREAD

**Issue by xytian315** [DigitalPebble/storm-crawler#600]
Sometimes we want to know more than just "FETCHED, REDIRECTION, FETCHED_ERROR". 
https://github.com/DigitalPebble/storm-crawler/blob/a2e47204cb2fd7c089cac7764d803a6013b867a9/core/src/main/java/com/digitalpebble/stormcrawler/persistence/Status.java

especially it seemed all 4XX and 5XX belongs to FETCHED_ERROR. Do you guys have plans to store specific "HTTP status code" in the ES status index?

**Comment by sebastian-nagel** [comment]
Isn't this already possible by adding `fetch.statusCode` to the list of persisted metadata (file `crawler-conf.yaml`):
```
metadata.persist:
- fetch.statusCode

```
