### ISSUE TITLE
what are the dependencies of storm crawler and where can i find the bundled jar files of those dependencies ?

### ISSUE THREAD

**Issue by saiprashanth24** [DigitalPebble/storm-crawler#601]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the best place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use StackOverflow
       instead with the label 'stormcrawler': https://stackoverflow.com/questions/tagged/stormcrawler 

 - [ ] Bug report. If you’ve found a bug, please include a test if you can, it makes it a lot easier to fix things. Use the label 'bug' on the issue.
 
 - [ ] Feature request. Please use the label 'wish' on the issue.

Thanks!

**Comment by jnioche** [comment]
Wrong place to ask questions and no effort to find the solution.
