### ISSUE TITLE
how to extend the scheduler class ?

### ISSUE THREAD

**Issue by saiprashanth24** [DigitalPebble/storm-crawler#603]
What kind of issue is this?

 - [x] Question. This issue tracker is not the best place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use StackOverflow
       instead with the label 'stormcrawler': https://stackoverflow.com/questions/tagged/stormcrawler 

 - [ ] Bug report. If you’ve found a bug, please include a test if you can, it makes it a lot easier to fix things. Use the label 'bug' on the issue.
 
 - [ ] Feature request. Please use the label 'wish' on the issue.

Thanks!

**Comment by jnioche** [comment]
@saiprashanth24 which part of 

> This issue tracker is not the best place for questions. If you want to ask how to do
something, or to understand why something isn't working the way you expect it to, use StackOverflow
instead with the label 'stormcrawler': https://stackoverflow.com/questions/tagged/stormcrawler

wasn't clear?
