### ISSUE TITLE
A simple HttpClient.execute slower than JSoup.connect

### ISSUE THREAD

**Issue by Serimert90** [DigitalPebble/storm-crawler#604]
*****************************Apache HttpCore 4.4.10**********************

CloseableHttpClient client = HttpClientBuilder.create()
                        .setUserAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0")
                        .setConnectionTimeToLive(1,TimeUnit.MINUTES)
                        .setMaxConnPerRoute(1000)
                        .setMaxConnTotal(1000)
                        .disableAutomaticRetries()
                        .build();
                HttpClientContext context = HttpClientContext.create();
                HttpGet request = new HttpGet("URL");

                // add request header
                request.addHeader("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0");
                HttpResponse response2 = client.execute(request,context);*/

*******************************JSOUP********************************

                Connection.Response response = Jsoup.connect("URL")
                        .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0")
                        .header("Accept-Encoding", "gzip, deflate")
                        .execute();

                cookies = response.cookies();

When trying with apache, it gives _org.apache.http.NoHttpResponseException: The target server failed to respond_ when automatic tries enabled .  but in the some _xth_ try it gives me the result in 1 seconds maybe. With  Jsoup it is very fast and instant.

What am i doing wrong?

**Comment by jnioche** [comment]
Hi @Serimert90, why don't you ask this to the Http Core mailing list or on StackOverflow? You'd get a more accurate answer.
