### ISSUE TITLE
Batch PreparedStatements in SQL status updater bolt

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#610]
Each document is currently updated in an individual call to SQL, which can be a bottleneck. It would be more efficient to batch the preparedstatements.

**Comment by jnioche** [comment]
@cruftex

**Comment by jnioche** [comment]
see also https://mariadb.com/kb/en/library/option-batchmultisend-description/

**Comment by cruftex** [comment]
http://java-persistence-performance.blogspot.com/2013/05/batch-writing-and-dynamic-vs.html

**Comment by cruftex** [comment]
Hi Julien,

unfortunately there are no automated tests for the SQL persistence component. That would make working on code improvements so much easier.

In our applications we use the H2 database engine with in memory mode for the tests and PostgreSQL in production. That works pretty fine. For the tests there is no need to setup a database then, which means it can run on every CI server.

Another thing: There are some MySQL specific functions used. I am not 100% sure, but it seems everything needed is pretty basic, so it should be possible to make everything database agnostic and just use plain SQL.

So I'd recommend to get rid of MySQL specifics and have some tests first. What do you think?

**Comment by cruftex** [comment]
Another thing: Some SQL databases have JSON support. It would be a good idea to change the metadata serialization format to JSON.

**Comment by jnioche** [comment]
Hi Jens, thanks for your comments. I like the idea of having tests + be database neutral.
Am working on a first version of the batching, will send a PR shortly. Would be great if you could review it, we can then refine it further.
