### ISSUE TITLE
ParserBolt to send outlinks to status stream, remove from default one?

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#66]
The [ParserBolt](https://github.com/DigitalPebble/storm-crawler/blob/master/src/main/java/com/digitalpebble/storm/crawler/bolt/ParserBolt.java) currently sends the outlinks to the default stream alongside the other fields for a document ("url", "content", "metadata", "text"). It would be better to send them to the status stream instead, as we do for the Sitemaps, redirections etc...

**Comment by jnioche** [comment]
If we decide to send the outlinks through the 'status' stream then it would be good to do it before the 0.4 release
@DigitalPebble/committers-crawler  any thoughts on this?

**Comment by GuiForget** [comment]
I'm ok with that

**Comment by jnioche** [comment]
see #67
