### ISSUE TITLE
Implement horizontal depth limit (qty of outlinks discovered by page)

### ISSUE THREAD

**Issue by jcruzmartini** [DigitalPebble/storm-crawler#669]
We have been having troubles crawling huge sites, so in order to limit the qty of pages that we are gonna be crawling in each site, would be awesome if we can implement an horizontal depth limit, that means that crawler wont discovery more than N outlinks per page. Where N is configurable 

_I am working on this now, will create a PR in the afternoon with some unit tests to cover this scenario if you do not have objections._

Thanks
Juan

What kind of issue is this?

 - [ ] Question. This issue tracker is not the best place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use StackOverflow
       instead with the label 'stormcrawler': https://stackoverflow.com/questions/tagged/stormcrawler 

 - [ ] Bug report. If you’ve found a bug, please include a test if you can, it makes it a lot easier to fix things. Use the label 'bug' on the issue.
 
 - [x] Feature request. Please use the label 'wish' on the issue.

Thanks!

**Comment by jnioche** [comment]
#670
