### ISSUE TITLE
Asynchronous spouts (i.e ES) can send queries after max delay since previous one ended 

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#683]
At the moment both synchronous and asynchronous spout implementations wait for the buffer to be empty before emitting a query. Since queries on a large index can take some time, this usually means that the spout waits idly and that the number of tuples in flight progressively goes down.

We already have a minimal delay for emitting a query after one has been sent so as to not swamp the backend when queries are fast. We could have a max delay since the previous request has been received and processed and if elapsed, force the query to be re-emitted even if the buffer is not empty.

**Comment by mstrewe** [comment]
It would be a good idea to query in advance to avoid idle times. 
2 Questions i have:

1. What ist does the `in_buffer` really do?
2. Would it make sence to check the size of the `in_progress` map and allow query in advance when it has fewer urls then x percent of `maxBucketNum * maxURLsPerBucket`? (e.g. x = 10)

**Comment by jnioche** [comment]
thanks for your comments @mstrewe 

> * What ist does the `in_buffer` really do?

Merely an optimisation. it gives us a way of checking that a URL is not already in the buffer when processing the results from ES. We could rely on _buffer.contains()_ but being a LinkedList it is likely to be inefficient whereas the HashSet will be fast.

> * Would it make sence to check the size of the `InProcessMap` map and allow query in advance when it has fewer urls then x percent of `maxBucketNum * maxURLsPerBucket`?

I considered doing something like that but the InProcessMap also contains URLs that have been processed succesfully and acked - not just the ones that are currently processing. Moreover, some crawls where most buckets have been exhausted and only a few buckets are left would probably trigger a query as soon as the previous one has finished. We could explore a variant of this idea later on.
