### ISSUE TITLE
upgrade okhttp to 3.14.0

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#692]

**Comment by jnioche** [comment]
from 3.11 - see https://github.com/square/okhttp/blob/master/CHANGELOG.md

in particular 

> OkHttp now offers full-operation timeouts. This sets a limit on how long the entire call may take and covers resolving DNS, connecting, writing the request body, server processing, and reading the full response body. If a call requires redirects or retries all must complete within one timeout period.
> 
> Use OkHttpClient.Builder.callTimeout() to specify the default duration and Call.timeout() to specify the timeout of an individual call.

**Comment by sebastian-nagel** [comment]
Yes, this feature might be useful. Although the savings are small as the `http.content.limit` still requires to request data in a loop in smaller blocks. #691 tracks the reason for trimmed content (content or time limit, or other exceptions): with a global callTimeout() it would require that all exceptions thrown by okhttp are analyzed to distinguish between timeouts and other exceptions.

**Comment by jnioche** [comment]
good point for not using it. Still worth upgrading for all the other bugfixe it contains
