### ISSUE TITLE
URLs without valid host name (and routing) stay DISCOVERED forever

### ISSUE THREAD

**Issue by sebastian-nagel** [DigitalPebble/storm-crawler#706]
From time to time I have to clean up URLs which fail to fetch and stay DISCOVERED forever. These URLs (eg., `http:/feeds/xml/latest.xml`) are valid in terms of bot java.net.URL and java.net.URI but lack a valid host name (empty for URL, null for URI).

My first thought was that #704 also addresses this issue but that isn't the case. The main difference: from the logs there is no evidence that any of these URLs without host name are tried to be fetched. The only log messages come from the
- feed parser (when checking robots.txt before #700):
```
2019-04-09 06:19:37.927 c.d.s.p.RobotRulesParser Thread-24-feed-executor[4 7] [INFO] Couldn't get robots.txt for http:/feeds/xml/latest.xml : java.net.UnknownHostException: robots.txt: Name or service not known
2019-04-09 06:19:37.928 c.d.s.b.FeedParserBolt Thread-24-feed-executor[4 7] [INFO] Feed parser done http://sportdog.gr/feeds/xml/latest.xml
```
- and StatusUpdaterBolt with debug logging:
```
2019-04-12 09:25:46.379 c.d.s.e.p.StatusUpdaterBolt Thread-16-status-executor[24 24] [DEBUG] Added to waitAck http:/feeds/xml/latest.xml with ID d9b44c50cbf08dc553acaab40fb8d9e58614e655c0738d19f2a481104d405ca2 total 1
2019-04-12 09:25:46.379 c.d.s.e.p.StatusUpdaterBolt Thread-16-status-executor[24 24] [DEBUG] Sending to ES buffer http:/feeds/xml/latest.xml with ID d9b44c50cbf08dc553acaab40fb8d9e58614e655c0738d19f2a481104d405ca2
2019-04-12 09:25:46.379 c.d.s.p.AdaptiveScheduler Thread-16-status-executor[24 24] [DEBUG] Scheduling status: DISCOVERED, metadata: discoveryDate: 2019-04-12T09:25:46.379Z
```

The invalid URL stems from an [Atom feed](http://sportdog.gr/feeds/xml/latest.xml):
```xml
    <entry>
        <title>Η Κωνσταντίνα Σπυροπούλου μας δείχνει τα κάλλη της με σέξι μπικίνι - Πρέπει να δεις αυτή τη φωτό!</title>
        <link rel="alternate" type="text/html" href="//#rurl_blhttp://newpost.gr/lifestyle/5caf3cec90e42f7a56d7db7a/i-konstantina-spyropoyloy-mas-deihnei-ta-kalli-tis-me-sexi-mpikini"/>
        <published>2019-04-11T17:09:00+00:00</published>
```

The mentioned URL is stored in the status index without a routing key (`metadata.hostname`):
```json
    "hits" : [
      {
        "_index" : "status",
        "_type" : "status",
        "_id" : "d9b44c50cbf08dc553acaab40fb8d9e58614e655c0738d19f2a481104d405ca2",
        "_score" : 0.2876821,
        "_source" : {
          "url" : "http:/feeds/xml/latest.xml",
          "status" : "DISCOVERED",
          "metadata" : {
            "url%2Epath" : [
              "http://sportdog.gr/feeds/xml/latest.xml"
            ],
            "depth" : [
              "1"
            ]
          },
          "nextFetchDate" : "2019-04-12T09:25:46.000Z"
        }
      }
    ]
```

One solution would be to filter these URLs away - if hostname is empty and protocol http/https - file URLs are allowed without host.

Alternatively, if the empty host or domain name should be allowed as routing key to make these items fail. Also (I haven't checked it): isn't the empty routing mandatory in a crawl which mixes http:// and file:// URLs?

**Comment by jnioche** [comment]
These URLs should be filtered indeed.

Not sure why this URL doesn't have its status updated. I tried with a simple topology from the archetype and the fetcher sends it to the statusupdaterbolt as a fetch error

_http:/feeds/xml/latest.xml	FETCH_ERROR	Fri Apr 12 17:41:18 BST 2019_

the statusupdaterbolt gets an empty partition key and does not do the sharding explicitely but the latter should be based on the _id which is generated from the URL so regardless of which shard this URL gets sent to, the behaviour should be consistent.

**Comment by sebastian-nagel** [comment]
I have:
```
# (es-conf.yaml)
  es.status.routing: true
  es.status.routing.fieldname: "metadata.hostname"
# (crawler-conf.yaml)
  partition.url.mode: "byDomain"
```

**Comment by jnioche** [comment]
Got it, this URL never gets fetched because the spouts group them by a field it does not have. The way in which it is sharded is irrelevant. I've just tested using an empty string for the sharding and as value for _metadata.hostname_ and it works fine: the URLs gets fetched and its status updated accordingly. Will commit a fix soon, thanks @sebastian-nagel

**Comment by jnioche** [comment]
@sebastian-nagel don't you use the HostURLFilter? It should have prevented the URL from being added

**Comment by sebastian-nagel** [comment]
The cross-domain filter has been disabled and later HostURLFilter has been entirely removed from the config. There can be cross-domain links from feeds, esp. sites "hosting" their feed on `feedburner.com`.

**Comment by jnioche** [comment]
makes sense. we could add a check for a valid hostname in the basic URL filter or normaliser
