### ISSUE TITLE
Upgrade to Elasticsearch 7.0.x

### ISSUE THREAD

**Issue by rzo1** [DigitalPebble/storm-crawler#708]
Upgrade Elasticsearch to 7.0.x (7.0.0 atm) (includes adjustments for Kibana 7.0.x) as well.

Breaking changes can be found here: 

https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html

Upgrade guideance:

https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html

As far as I can see, we will have to deal with some deprecated stuff in `DeletionBolt` and `StatusMetricsBolt`. 

In addition, `docType` is in the process of being removed in the near future (see JavaDoc of `DeleteRequest`)

In addition `DEFAULT_MAX_RETRY_TIMEOUT_MILLIS` used in `ElasticSearchConnection` seems to be removed as well (see https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#breaking_70_restclient_changes for details) without an replacement.

**Comment by jnioche** [comment]
hi! do you know we already have a branch for it?
https://github.com/DigitalPebble/storm-crawler/tree/es-7

Feedback welcome as usual

**Comment by rzo1** [comment]
Hey @jnioche 

wuhu - thanks for the response. I did not checked this branch as I did not found an related issue.

I will give it a try!

**Comment by rzo1** [comment]
I did some testing - no issues yet. Will continue to build our depending artifacts against the es-7 branch (merged with the latest master changes)

**Comment by jnioche** [comment]
Will be in the 1.14 release then
https://twitter.com/stormcrawlerapi/status/1124259162039422977
