### ISSUE TITLE
Pre-release tasks

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#71]
- Apply formatting to the whole code
- update README file to include `core` in paths and jar names

**Comment by jakekdodd** [comment]
I'll tackle the documentation

**Comment by jnioche** [comment]
I already updated README

**Comment by jakekdodd** [comment]
Should we illustrate using `storm-crawler-core` and `storm-crawler-external` as separate maven dependencies?

Also, I was going to create READMEs for each submodule

**Comment by jnioche** [comment]
Maybe let's just mention -external and show how to use it in Maven. I don't think we need separate READMEs, there isn't much to say about external.
What we should do is have a separate WIKI page describing the resources in external.

**Comment by GuiForget** [comment]
I submitted a PR which cleans up the code

**Comment by GuiForget** [comment]
The javadoc issue is also fixed. I'm now able to run `mvn package -P release` without any errors

**Comment by jnioche** [comment]
thanks, will release shortly

**Comment by jakekdodd** [comment]
Yep `mvn package -P release` builds the javadocs without any errors. :+1:

**Comment by jnioche** [comment]
The release candidate for 0.4 can be found on \:
[https://oss.sonatype.org/content/repositories/comdigitalpebble-1007/com/digitalpebble/]

@DigitalPebble/committers-crawler please have a look at it and confirm that it can be released. 

I opened #76 but this can be done for the next release I think. Thanks!

**Comment by jnioche** [comment]
Note that a release tag has already been created [https://github.com/DigitalPebble/storm-crawler/releases/tag/0.4] and the versions have been upped automatically in the code but we can revert to the previous values if you find something serious and we need to spin a new RC.

**Comment by jnioche** [comment]
Have published the release, the artefacts will be in Maven Central soon. Let's do a 0.4.1 if we find that something is wrong.
