### ISSUE TITLE
Review Robots' caching logic

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#713]
@sebastian-nagel's comment on #709 (96eff4c)

> Wouldn't this mean that the rules read from /robots.txt of the redirection host are always taken, no matter what the path of redirect target is? One example:
> 
> https://host-a.example.org/robots.txt redirects to https://static.example.org/host-a/robots.txt
> keyredir of the redirect target is https:static.example.org:443
> but under this key the rules from https://static.example.org/robots.txt are hold
> The logic should be the other way around: only if the path of the redirect target equals /robots.txt, the rules can be taken from the cache using the key of the redirect target.

**Comment by sebastian-nagel** [comment]
Is this in progress? Otherwise I would try to get it fixed.

**Comment by jnioche** [comment]
Am not working on it, would be great if you could have a go. Thanks
