### ISSUE TITLE
withRequestRecords can cause ConcurrentModificationException on the metadata

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#721]
When running a web archiving topology with 2 workers running on a single machine and with the WARC bolt connected straight to the FetcherBolt with the rest of the topology (parsing, updating) connected to the FetcherBolt as well, I am getting a  ConcurrentModificationException on the Metadata.

This is strange as I was expecting the tuples to be serialized between bolts but this would indicate that the instance is shared between bolts. The [WARCRequestRecordFormat](https://github.com/DigitalPebble/storm-crawler/blob/48c34777fd9708e20c1c27f68832e150a67e4d68/external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCRequestRecordFormat.java#L68) writes to the metadata after it has been emitted by one of other bolts, which causes the exception.

This does not happen when _withRequestRecords_ is not used.  WARCRecordFormat relies on the key "_request.warc_record_id_" in the metadata to link the request with the response.

As a solution, we could make a copy of the tuple in MultipleRecordFormat so that WARCRequestRecordFormat can write to the metadata and WARCRecordFormat can read from it without affecting the other bolts.

**Comment by jnioche** [comment]
@sebastian-nagel this is probably a bug in Storm and I can't work out a clean solution to this problem. Would it be OK to temporarily comment out 

 ```       metadata.addValue("_request.warc_record_id_", mainID); ```

until the root of the problem is found? This way we could release 1.14

**Comment by sebastian-nagel** [comment]
Luckily, the [WARC-Concurrent-To](http://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/#warc-concurrent-to) is not mandatory, so this may be an option.

From the [1.2.2 storm docs](http://storm.apache.org/releases/1.2.2/Troubleshooting.html):

> Everything you emit into the output collector must be immutable. What's happening is that your bolt is modifying the object while it is being serialized to be sent over the network.

I've tried to reproduce the issue but without success so far.

**Comment by jnioche** [comment]
I've reproduced the issue on another server and it doesn't happen when commenting the line above. Will commit shortly.
