### ISSUE TITLE
[Bug] RemoteDriverProtocol does not set user agent correctly

### ISSUE THREAD

**Issue by GerbenKD** [DigitalPebble/storm-crawler#735]
The RemoteDriverProtocol class scans for the `$useragent` String here (in RemoteDriverProtocol):

                Entry<String, Object> entry = iter.next();
                Object val = entry.getValue();
                // substitute variable $useragent for the real value
                if (val instanceof String
                        && "$useragent".equalsIgnoreCase(val.toString())) {
                    val = userAgentString;
                }
                capabilities.setCapability(entry.getKey(), entry.getValue());

However, the changed value is never actually used, instead the orginal value in the entry is used.
Related, I'm not sure this is the right way to set the user-agent for Chrome.

cheers and thanks,

Gerben

**Comment by jnioche** [comment]
thanks @GerbenKD, should now be fixed

feel free to open a PR if you find that Chrome requires a different mechanism
