### ISSUE TITLE
Index pages with content="noindex,follow" meta tag

### ISSUE THREAD

**Issue by AliAzG** [DigitalPebble/storm-crawler#750]
Some pages with `<meta name="robots" content="noindex,follow"/> ` tag, can not get indexed in _docs_ in SOLR.
Need to add some configs to skip these kinds of tags.

**Comment by jnioche** [comment]
There can be legitimate reasons to ignore robots directives from html meta tags or http headers. Have added the functionality to do so in 7077243b

The following elements are now in the default configuration

```
  # ignore directives from robots.txt files?
  http.robots.file.skip: false
  
  # ignore robots directives from the http headers?
  http.robots.headers.skip: false
  
  # ignore robots directives from the html meta?
  http.robots.meta.skip: false
```
There is a breaking change as the previous config name for the robots files was `http.skip.robots`, which I changed to `http.robots.file.skip`
