### ISSUE TITLE
Implement WARC spout

### ISSUE THREAD

**Issue by sebastian-nagel** [DigitalPebble/storm-crawler#755]
A "WARC spout" could read records from WARC files and emit tuples <URL, content, metadata> into the topology, similar as done by FetcherBolt. This would allow
- to reproducibely test and benchmark the topology (parser, indexer and status update bolts) with the same "frozen" data
- to use parts of a crawl topology to process historic data from WARC files using the same parsers and indexers
- to easily rewrite or (re)index WARC files, cf. #567

**Comment by kkrugler** [comment]
Just FYI, there's a Common Crawl fetcher that's part of the flink-crawler project, which we used extensively during testing as a way of having a large-scale, reproducible crawl. See https://github.com/ScaleUnlimited/flink-crawler/tree/master/src/main/java/com/scaleunlimited/flinkcrawler/fetcher/commoncrawl

**Comment by sebastian-nagel** [comment]
Thanks, @kkrugler: a fetcher which gets the content from WARC files via a CDX index would be a further step. For now, my idea was simpler: just consume a list of WARC files and emit all records into the topology. It's just a "replay" of an already recorded crawl.
