### ISSUE TITLE
Fix release artefacts

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#76]
The release is done with the following commands \:

mvn release:clean release:prepare -P release
mvn release:perform -P release

Since refactoring into core and external I am seeing the following 

*uber-jar published for core* 

.../content/com/digitalpebble/storm-crawler-core/0.4/storm-crawler-core-0.4-jar-with-dependencies.jar

which should not have happened since I specify the 'release' profile.

*generated tests for parent pom* 

.../com/digitalpebble/storm-crawler/0.4/storm-crawler-0.4-tests.jar

which should not have happened.

Any ideas? I will release 0.4 with these but it would be good to fix that for the next release

**Comment by jnioche** [comment]
and maybe rename the parent pom into 'storm-crawler-parent' to prevent any confusion as 'storm-crawler' used to contain the code but does not anymore

**Comment by jakekdodd** [comment]
Should be easy fixes, I'll get on that.

**Comment by jakekdodd** [comment]
Addressed in #80
