### ISSUE TITLE
java.lang.ClassCastException: clojure.lang.PersistentVector cannot be cast to java.lang.String at com.digitalpebble.stormcrawler.util.ConfUtils.getString

### ISSUE THREAD

**Issue by billiamchoi** [DigitalPebble/storm-crawler#769]
I follow tutorial on http://stormcrawler.net/getting-started/ by watching youtube.

After I type fallowing line on my command line

I got error on my spout

storm jar target/tutorial-1.0-SNAPSHOT.jar  org.apache.storm.flux.Flux --remote es-crawler.flux

![스크린샷 2019-11-15 오후 6 08 20](https://user-images.githubusercontent.com/48000438/68931146-4710d200-07d3-11ea-9881-a5b9164d426d.png)

the error log is like this :

java.lang.ClassCastException: clojure.lang.PersistentVector cannot be cast to java.lang.String at com.digitalpebble.stormcrawler.util.ConfUtils.getString(ConfUtils.java:74) at com.digitalpebble.stormcrawler.elasticsearch.persistence.AbstractSpout.open(AbstractSpout.java:183) at com.digitalpebble.stormcrawler.elasticsearch.persistence.AggregationSpout.open(AggregationSpout.java:96) at org.apache.storm.daemon.executor$fn__10112$fn__10127.invoke(executor.clj:609) at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:482) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:748)

Can you guys please give me a hint or solution to this error log?

I use

elasticsearch version 7.4.2 
kibana version 7.4.2
storm version 1.2.3
and my computer is mac

**Comment by jnioche** [comment]
Hi @billiamchoi,

In the future, could you please ask questions like these on StackOverflow with the tag 'stormcrawler'? you'd get a larger audience.

This [video](https://www.youtube.com/watch?v=KTerugU12TY) has been done more than 2 years and some of it is probably outdated. The version of SC used in the video (1.5) won't be compatible with ES 7.x anyway.

Looks like you are passing a list in the config where the code expects a String. Would you mind sharing your ES configuration file?

The error message you posted is a bit puzzling as [line 183 does not call Confutils](https://github.com/DigitalPebble/storm-crawler/blob/1.5/external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AbstractSpout.java#L183)  version 1.5 of SC.

Could you please check the version of SC in the pom file?

Thanks!

**Comment by billiamchoi** [comment]
in my es-conf.yaml

# configuration for Elasticsearch resources
  
config:
  # ES indexer bolt
  # adresses can be specified as a full URL
  # if not we assume that the protocol is http and the port 9200
  es.indexer.addresses: "localhost"
  es.indexer.index.name: "content"
  # es.indexer.pipeline: "_PIPELINE_"
  es.indexer.create: false
  es.indexer.bulkActions: 100
  es.indexer.flushInterval: "2s"
  es.indexer.concurrentRequests: 1
  es.indexer.settings:
    cluster.name: "elasticsearch"
  
  # ES metricsConsumer
  es.metrics.addresses: "http://localhost:9200"
  es.metrics.index.name: "metrics"
  es.metrics.settings:
    cluster.name: "elasticsearch"
  
  # ES spout and persistence bolt
  es.status.addresses: "http://localhost:9200"
  es.status.index.name: "status"
  #es.status.user: "USERNAME"
  #es.status.password: "PASSWORD"
  # the routing is done on the value of 'partition.url.mode'
  es.status.routing: true
  # stores the value used for grouping the URLs as a separate field
  # needed by the spout implementations
  # also used for routing if the value above is set to true 
  es.status.routing.fieldname: "key"
  es.status.bulkActions: 500
  es.status.flushInterval: "5s"
  es.status.concurrentRequests: 1
  es.status.settings:
    cluster.name: "elasticsearch"
  
  ################
  # spout config #
  ################
  
  # positive or negative filters parsable by the Lucene Query Parser
  # es.status.filterQuery: 
  #  - "-(key:stormcrawler.net)"
  #  - "-(key:digitalpebble.com)"

  # time in secs for which the URLs will be considered for fetching after a ack of fail
  spout.ttl.purgatory: 30
  
  # Min time (in msecs) to allow between 2 successive queries to ES
  spout.min.delay.queries: 2000

  # Delay since previous query date (in secs) after which the nextFetchDate value will be reset to the current time
  # Setting this to -1 or a large value means that the ES will cache the results but also that less and less results
  # might be returned.
  spout.reset.fetchdate.after: 120

  es.status.max.buckets: 50
  es.status.max.urls.per.bucket: 2
  # field to group the URLs into buckets
  es.status.bucket.field: "key"
  # fields to sort the URLs within a bucket
  es.status.bucket.sort.field: 
   - "nextFetchDate"
   - "url"
  # field to sort the buckets
  es.status.global.sort.field: "nextFetchDate"

  # CollapsingSpout : limits the deep paging by resetting the start offset for the ES query 
  es.status.max.start.offset: 500
  
  # AggregationSpout : sampling improves the performance on large crawls
  es.status.sample: false

  # max allowed duration of a query in sec 
  es.status.query.timeout: -1

  # AggregationSpout (expert): adds this value in mins to the latest date returned in the results and
  # use it as nextFetchDate
  es.status.recentDate.increase: -1
  es.status.recentDate.min.gap: -1

  topology.metrics.consumer.register:
       - class: "com.digitalpebble.stormcrawler.elasticsearch.metrics.MetricsConsumer"
         parallelism.hint: 1
         #whitelist:
         #  - "fetcher_counter"
         #  - "fetcher_average.bytes_fetched"
         #blacklist:
         #  - "__receive.*"

and my storm cralwer version is 1.4 

should I use lower version of ES? 

And sorry about putting this kind of question in github issue.

It was my first question. 

In future I will use StackOverflow

**Comment by jnioche** [comment]
> And sorry about putting this kind of question in github issue.
> 
> It was my first question.
> 
> In future I will use StackOverflow

No problem at all!

I think the problem comes from the fact that you are using the config for the current version of SC but SC 1.4. In particular, _  es.status.bucket.sort.field_ wasn't multivalued until recently. 

Either use the [version of the conf](https://github.com/DigitalPebble/storm-crawler/blob/1.4/external/elasticsearch/es-conf.yaml) that is compatible with your version of SC, or better, use the latest SC. Please note that the  conf on the master branch does not match the latest release, again, get it from [tag 1.15](https://github.com/DigitalPebble/storm-crawler/blob/1.15/external/elasticsearch/es-conf.yaml). 

Let me know how it goes.

**Comment by billiamchoi** [comment]
Thanks, @jnioche 
I solve the problem by restart storm crawler based project version 1.15
I git cloned master branch of storm cralwer which I think It is version 1.14
you gave me ilnk of tag 1.15 version of storm crawler and I changed es-conf.yaml
It works fine thanks to you

I have extra question..

Top K100 2016.txt file works very well as seeds.txt

but I want to crawl website for a instance..

https://www.kaggle.com/
https://www.data.gov/

I noticed that Injector works fine and 
elasticsearch said that it is  status: 'discovered'
but I don't get any of status:fetched by those kind of websites
Is there diffence between topk2016 site and two websites that I mentioned?

Anyway It was really kind of you to reply on my issue

Sincerely, billiamchoi

**Comment by jnioche** [comment]
I can't see anything obviously wrong with these 2 sites. Please ask on StackOverflow if you can't solve the problem.
