### ISSUE TITLE
status index / Adaptive scheduler: get rid of last-modified dates in non-ISO date format

### ISSUE THREAD

**Issue by sebastian-nagel** [DigitalPebble/storm-crawler#777]
There are still quite a few "last-modified" dates not in ISO date format, e.g.:
``` json
"_source" : {
  "url" : "https://zz.te.ua/feed/",
  "status" : "FETCHED",
  "metadata" : {
    "last-modified" : [
      "Thu, 12 Dec 2019 20:00:57 GMT"
    ],
    "signature" : [
      "9fde2d107d3339060a178fa8a59a55da"
    ],
    "fetchInterval" : [
      "432"
    ],
    "isFeed" : [
      "true"
    ],
    "fetch%2EstatusCode" : [
      "200"
    ],
    "signatureChangeDate" : [
      "2019-12-12T21:44:57.948Z"
    ],
    "hostname" : "zz.te.ua"
  },
  "nextFetchDate" : "2019-12-13T13:02:41.000Z"
}
```

Protocol implementations expect the last-modified time to be in ISO format (see #673) - if the ISO format is not followed, they do not send the "If-not-modified-since" header.

With #496 the adaptive scheduler uses the ISO date-time format to store the last-modified time.
However, the adaptive scheduler only sets the last-modified time when the comparison of the current and the previous signature indicates a content change. It never sets the last-modified time
1. for the initial fetch of a page (no signatures to compare) or
2. if the pages has not changed (HTTP 304 or same signature)
3. if another scheduler is used

In these situations, if the server sends a "Last-modified" header with the response, this value overwrites the existing one. There two issues with the value from the "Last-modified" header:
- the date format
- we cannot trust the date:
  - it could be a time in the future or even implausible far in the past
  - or just off few hours because of time zone issues or just the clock going wrong

"If-modified-since" requests should always use the date of the last fetch (if successful).

To overcome the issue:
1. use a different metadata field than "last-modified" for either AdaptiveScheduler or to hold the response metadata (see #776)
2. let AdaptiveScheduler set "last-modified" for initial fetches (or first successful fetch after a fetch error or redirect status)

**Comment by sebastian-nagel** [comment]
Alternative solution without changes of metadata field names:
-  AdaptiveScheduler
   - sets "signatureChangeDate" also at the initial fetch
   - always overwrites "last-modified" with "signatureChangeDate" so that the "last-modified" field holds a well-formatted date or is empty after non-successful fetches
- both "last-modified" and "signatureChangeDate" are required to be persisted (both containing the same value)

**Comment by jnioche** [comment]
hi @sebastian-nagel 
sorry for the late reply

could we simply ignore _last-modified_ altogether and rely on _signatureChangeDate_ only? in that case the 2nd option w/o change of metadata would be preferable and whatever is set by the servers for  _last-modified_ becomes irrelevant.

how would this affect the default behaviour when not using the AdaptiveScheduler?

**Comment by sebastian-nagel** [comment]
1. we would also need to set _signatureChangeDate_ for successful fetches (HTTP 200 Ok)
   - (using AdaptiveScheduler) for the initial fetch
   - (without AdaptiveScheduler) for all successful fetches: could be done in DefaultScheduler
2. the change affects all HTTP protocol implementations: read the value sent in the "If-Modified-Since" header from _signatureChangeDate_ instead of _last-modified_ - But what about #776? Dependent on the decision there, we could continue to use _last-modified_ and set it appropriately in both schedulers.

**Comment by jnioche** [comment]
I am inclined to postponed this after the next release. This and #776 are not trivial and I'd rather have time to think it through without blocking the release. What do you think @sebastian-nagel ?

**Comment by sebastian-nagel** [comment]
Ok to carefully think about a good solution.
