### ISSUE TITLE
parsefilters.config.file and urlfilters.config.file location

### ISSUE THREAD

**Issue by ravi-b-m** [DigitalPebble/storm-crawler#796]
Based on this
[JSONResource.java](https://github.com/DigitalPebble/storm-crawler/blob/14ed86dbeb39e9af550f24a2914a9f32ba869463/core/src/main/java/com/digitalpebble/stormcrawler/JSONResource.java#L51)

I cannot externalize my `parsefilters.json` and `urlfilters.json`, do I need to embed them in my uber jar ?

**Comment by jnioche** [comment]
yes. simply put them in src/main/resources

BTW please ask questions like these on Stackoverflow with the tag Stormcrawler.
