### ISSUE TITLE
[Bug] Storm Crawler 2.0 -conf arguments no longer work

### ISSUE THREAD

**Issue by jdpedrie** [DigitalPebble/storm-crawler#817]
In Storm Crawler 1.x, we were able to provide additional configuration files via the `-conf` argument when starting a topology. In Storm Crawler 2.0, this no longer works.

```sh
$ /path/to/storm/bin/storm jar app.jar \
	com.foo.bar.topology.MyTopology \
	-conf /path/to/config.yaml
```

In Storm Crawler 1.16, inspecting the value of `args` in [`ConfigurableTopology.start`](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/stormcrawler/ConfigurableTopology.java#L43) shows the following:

```
args:
	0: "-conf"
	1: "/path/to/config.yaml"
```

In Storm Crawler 2.0, the same command shows the value of `args` as:

```
args:
	0: "/path/to/config.yaml"
```

Since `ConfigurableTopology.parse` disambiguates args based on the `-conf` prefix, this apparent upstream change in Storm has caused custom configuration files to no longer work.

**Comment by sebastian-nagel** [comment]
See d77b80a and the updated README.

**Comment by jdpedrie** [comment]
That did the trick. Thanks for the quick reply!
