### ISSUE TITLE
HTTP protocol implementation: allow to configure which protocol version(s) to use

### ISSUE THREAD

**Issue by sebastian-nagel** [DigitalPebble/storm-crawler#827]
It should be possible to configure which HTTP protocol versions (HTTP/1.1, HTTP/2, etc.) are used by a protocol implementation:
- WARC readers may fail on yet unknown HTTP protocol versions (see [discussion "Is there an option to use HTTP/1.0 or 1.1 for the Warc File"](https://groups.google.com/g/digitalpebble/c/VgoLRAnQDV0/m/bUrod9jxAAAJ), commoncrawl/news-crawl#42)
- but could be also useful for debugging and testing

**Comment by jnioche** [comment]
fixed in #829
