### ISSUE TITLE
[WARC] Backward compatible storage of HTTP/2 headers

### ISSUE THREAD

**Issue by sebastian-nagel** [DigitalPebble/storm-crawler#828]
Enable WARCHdfsBolt resp. WarcRecordFormat to write failure-proof files when using HTTP/2 - do not use "HTTP/2" in the status line as this may crash some WARC parsers. See iipc/warc-specifications#15 and iipc/warc-specifications#42 which proposes a field `WARC-Protocol`. Needs clarification how to store HTTP/2 requests and responses, meanwhile HTTP/2 can be disabled by #827.

**Comment by jnioche** [comment]
Fixed in #1010
