### ISSUE TITLE
Metadata emitted in fetcher

### ISSUE THREAD

**Issue by jakekdodd** [DigitalPebble/storm-crawler#83]
I noticed that, in some places, we emit `response.getMetadata()` and in other places, we emit `metadata` within FetcherBolt and SimpleFetcherBolt.

The `response.getMetadata()` includes all of the original tuple `metadata` (if extant). Is there a reason for emitting only the original tuple `metadata` in some situations? Particularly when emitting to the status stream, it might be beneficial downstream to do something with the HTTP response metadata.

**Comment by jnioche** [comment]
+1

**Comment by jakekdodd** [comment]
Addressed by 160b9d4dbe850e0f9dfa57f7a9e5253568282d54
