### ISSUE TITLE
Images are not displayed with url that contains utf-8 special symbols

### ISSUE THREAD

**Issue by MindaugasArsulis** [DigitalPebble/storm-crawler#830]
I made a warc file with storm-crawler and in this website - https://lietuva.lt/ - images are represented as:

div class="fold" style="background-image: url('https://lietuva.lt/wp-content/uploads/2019/07/VMG-Alfas-Ivanauskas-šaltibarščiai.jpg')"

when I open my crawled warc file with pywb I get:

div class="fold" style="background-image: url('http://localhost:8080/my-web-archive/20201002045755/https://lietuva.lt/wp-content/uploads/2019/07/VMG-Alfas-Ivanauskas-%C3%85%C2%A1altibar%C3%85%C2%A1%C3%84%C2%8Diai.jpg')"

it seems that image url is being converted to utf-8 several times.
When I open same warc file with Webrecorder.io I get correct encoding:

div class="fold" style="background-image: url('https://lietuva.lt/wp-content/uploads/2019/07/VMG-Alfas-Ivanauskas-šaltibarščiai.jpg')"

and image is displayed.

So I guess I should change these url links in warc html to encoded ones. How should I do that?

**Comment by sebastian-nagel** [comment]
The page content is written literally to the WARC files, the HTML (or any other payload, binary or not) is not modified. The playback software [rewrites](https://pywb.readthedocs.io/en/latest/manual/rewriter.html) the HTML so that links and page dependencies (images, CSS) are loaded from the archives and not from their original location.

Could you verify whether URLs in the WARC are recorded properly in the WARC files. Just grep for the mentioned snippet:
```
gzip -dc xyz.warc.gz | grep -F "url('https://lietuva.lt/wp-content/uploads/2019/07/VMG"
```

**Comment by MindaugasArsulis** [comment]
Thank you for your answer.

When you said it is not possible to change url to encoded ones, I have started to look at pywb. And strangely, when I run pywb thru the console, I can't see those pictures, but if I run it with intellij, pictures are shown. I have no idea why. But it works one way and it doesn't work the other

**Comment by sebastian-nagel** [comment]
Tried it using the Docker "webrecorder/pywb" and looks like the URL is encoded correct in the browser: `background-image: url('http://localhost:8080/default/20201006090923oe_/https://lietuva.lt/wp-content/uploads/2019/07/VMG-Alfas-Ivanauskas-%C5%A1altibar%C5%A1%C4%8Diai.jpg');`

Just curious: did you manage that stormcrawler includes all page dependencies to be included in the WARC files? That's not trivial, esp. for URLs are in style attributes.

**Comment by MindaugasArsulis** [comment]
> Just curious: did you manage that stormcrawler includes all page dependencies to be included in the WARC files?

Yes, I have managed that. I need to make warc files with as close to orginal website style as possible. 

I have noticed that when I open warc, browser console tells me, that it can't seem to find woff files. And I can't find them in page source. Maybe you know where to look for them?

**Comment by sebastian-nagel** [comment]
> Yes, I have managed that.

If this is no secret magic, would be great if you could share how to achieve this, eg. on the [warc module README](/DigitalPebble/storm-crawler/blob/master/external/warc/README.md)

> woff files

Web fonts are usually requested via `@font-face` constructs in the CSS, eg. in the [style.css](https://lietuva.lt/wp-content/themes/lietuva/assets/style.css?ver=20191002)

**Comment by jnioche** [comment]
great discussion and fab to see our WARC module being used
@MindaugasArsulis I'd be interested in hearing about the context of your work. Could you drop me a line at julien@digitalpebble.com? Thanks

**Comment by jnioche** [comment]
Can this be closed?
