### ISSUE TITLE
WARCSpout doesn't handle http.content.limit -1 correctly

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#850]
-1 is the value it takes by default if not set in the config and it means that the content should not be trimmed, just like the Fetcher Bolts do, however it doesn't handle it correctly and tries to trim to a negative value.
A temporary workaround is to configure it with a large value

`  http.content.limit: 99999999`

**Comment by jnioche** [comment]
@sebastian-nagel do you want to have a look at this one or shall I?

**Comment by sebastian-nagel** [comment]
Ok, I'll have a look.
