### ISSUE TITLE
Protocol implementations: Integer.MAX_VALUE not save as max. content size 

### ISSUE THREAD

**Issue by sebastian-nagel** [DigitalPebble/storm-crawler#854]
The protocol implementations (httpclient, okhttp, file) use Integer.MAX_VALUE for the maximum size of allowed content. While int_max is the limit of the array index, the max. allocatable array size is few bytes smaller and depends on the JVM, see [do-java-arrays-have-a-maximum-size](https://stackoverflow.com/questions/3038392/do-java-arrays-have-a-maximum-size). Maybe use [fastutil's Arrays.MAX_ARRAY_SIZE](http://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/Arrays.html#MAX_ARRAY_SIZE) which is Integer.MAX_VALUE - 8 ?

**Comment by jnioche** [comment]
Well, everything will probably explode if we get to anything that big ;-) 
Let's use  _Integer.MAX_VALUE - 8_  but without introducing a dependency on fastutils.
Thanks!
