### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.Integer org.apache.storm.utils.Utils.getInt(java.lang.Object)'

### ISSUE THREAD

**Issue by AaronNGray** [DigitalPebble/storm-crawler#856]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the best place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use StackOverflow
       instead with the label 'stormcrawler': https://stackoverflow.com/questions/tagged/stormcrawler 

 - [x ] Bug report. If you’ve found a bug, please include a test if you can, it makes it a lot easier to fix things. Use the label 'bug' on the issue.
 
 - [ ] Feature request. Please use the label 'wish' on the issue.

I am getting the following :-
```
storm jar target/storm-crawler-elasticsearch-1.0-SNAPSHOT.jar global.climateemergency.ESCrawlTopology -conf crawler-conf.yaml -conf es-conf.yaml -local . seeds.txt
Running: java -client -Ddaemon.name= -Dstorm.options=onf,onf -Dstorm.home=/mnt/c/Users/aaron/Development/apache-storm-2.2.0 -Dstorm.log.dir=/mnt/c/Users/aaron/Development/apache-storm-2.2.0/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib:/usr/lib64 -Dstorm.conf.file= -cp /mnt/c/Users/aaron/Development/apache-storm-2.2.0/*:/mnt/c/Users/aaron/Development/apache-storm-2.2.0/lib-worker/*:/mnt/c/Users/aaron/Development/apache-storm-2.2.0/extlib/*:target/storm-crawler-elasticsearch-1.0-SNAPSHOT.jar:/mnt/c/Users/aaron/Development/apache-storm-2.2.0/conf:/mnt/c/Users/aaron/Development/apache-storm-2.2.0/bin: -Dstorm.jar=target/storm-crawler-elasticsearch-1.0-SNAPSHOT.jar -Dstorm.dependency.jars= -Dstorm.dependency.artifacts={} global.climateemergency.ESCrawlTopology crawler-conf.yaml es-conf.yaml -local . seeds.txt
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.Integer org.apache.storm.utils.Utils.getInt(java.lang.Object)'
        at com.digitalpebble.stormcrawler.util.ConfUtils.getInt(ConfUtils.java:46)
        at global.climateemergency.ESCrawlTopology.run(ESCrawlTopology.java:55)
        at com.digitalpebble.stormcrawler.ConfigurableTopology.start(ConfigurableTopology.java:50)
        at global.climateemergency.ESCrawlTopology.main(ESCrawlTopology.java:48)
```
I am on Ubuntu on Windows WSL, I will try on my Linux Debian system ....

**Comment by sebastian-nagel** [comment]
Hi @AaronNGray, the main branch of StormCrawler is based on Storm 1.2.3 - there is a branch for Storm 2.x but afaik it's still recommended to use Storm 1.2.3.

**Comment by jnioche** [comment]
hi @AaronNGray, Seb is right: you are using a topology based on SC 1 on a Storm 2 cluster. You can either use a Storm 1 cluster instead or use the SC 2 branch.

**Comment by AaronNGray** [comment]
Ah I have been using Maven generated code and following your documentation and the generated documentation. AFAICT I think something needs updating somewhere !

**Comment by AaronNGray** [comment]
Is StormCrawler 2.x on Maven ?

**Comment by jnioche** [comment]
https://mvnrepository.com/artifact/com.digitalpebble.stormcrawler/storm-crawler-core/2.0
