### ISSUE TITLE
in domain depth and out domain depth

### ISSUE THREAD

**Issue by zhongwei2014** [DigitalPebble/storm-crawler#862]
Can we have a separate depth configuration for in domain and out of domain. For example, I would like to crawl the outside url if it is a direct outlink from this domain, but I don't want to crawl the whole site of the other domain, can I set the in_domain depth to 100, and outside domain depth to 0?

**Comment by sebastian-nagel** [comment]
I do not fully understand your use case
- with depth = 0 the filter "MaxDepthFilter" would not follow any outlinks
- depth = 1 would mean you allow one outlink, but would you also accept links to the external domain from deep pages on your source domain? Or only from the seed / home page?

The [filter method](/DigitalPebble/storm-crawler/blob/2d4ed3d28a943198c85dead2715e102593f09cad/core/src/main/java/com/digitalpebble/stormcrawler/filtering/depth/MaxDepthFilter.java#L55) gets both source and target URL as arguments, so it can be modified to fit your use case. E.g., in case of a link to an external domain increment the depth by 100.

A final note: the filter "HostURLFilter" provides an option `ignoreOutsideDomain`, if true links to external domains are not followed at all.

**Comment by jnioche** [comment]
that's a great question @zhongwei2014, thanks! There are probably several ways to do that.

You could for instance write a custom ParseFilter first so that outlinks outside the original domain get a key / value in their metadata when the source page is parsed, then write a custom URL Filter so that any outlinks found later on for a page with that key in its metadata get removed. You will need to add that key to   _metadata.persist_ in your config.

Does that make sense?

**Comment by jnioche** [comment]
the problem with the solution above is that it won't work for redirections, only for outlinks. I'll have a think and come back later with a different suggestion.

**Comment by jnioche** [comment]
@zhongwei2014 the best way to do it would be to extend the default implementation of [MetadataTransfer](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/stormcrawler/util/MetadataTransfer.java) and in  _getMetaForOutlink()_ increment the depth by whichever value is beyond your threshold if the source and target belong to different domains. this would work for outlinks as well as redirections.
The transfer is pluggable and you can set the implementation to use via _metadata.transfer.class_ in the config.
Let us know if it worked for you

**Comment by zhongwei2014** [comment]
Thanks. I was thinking about extending a filter (depth or host) class, but this might be a better place. I will let you know.
Thanks.

**Comment by jnioche** [comment]
Closing for now, please reopen if the solution I suggested didn't work @zhongwei2014
