### ISSUE TITLE
[Patch] Update the Wiki to include more configuration information and some hierarchy

### ISSUE THREAD

**Issue by psa-neutronian** [DigitalPebble/storm-crawler#864]
I've gone through the components in core and updated the documentation to include every call to ConfUtils. I've also added a bit of structure (folders and a custom sidebar) to make it a little easier to find things.

Here's the commits: https://github.com/psa/storm-crawler-wiki/commits/config-updates
Here's what they look like: https://github.com/psa/storm-crawler-wiki/wiki

Unfortunately, wiki's don't have the ability to do pull requests so the merge needs to be done as a clone + rsync or similar. 

I plan on doing the external modules next, feedback appreciated.

This work paid for by https://neutronian.com/

**Comment by psa-neutronian** [comment]
To make pull requests on the wiki easier, could a separate repository be created that automatically synchronizes to the wiki, similar to what's being doing in https://github.com/devonfw/devon4j/blob/develop/.travis.yml?

**Comment by jnioche** [comment]
Thanks a lot @psa-neutronian, I will have a look at your changes and the mechanism to sync the WIKI.
Alternatively, I could also give you write access to the WIKI.
Is StormCrawler used by Neutronian?

**Comment by psa-neutronian** [comment]
If you're happy with giving me wiki write access, I'm happy to do updates. Any review process?

Neutronian is considering using it and doing due diligence before diving in.

**Comment by jnioche** [comment]
Have temporarily given you rights access. Given that it is not possible to PR the WIKI, I'll just review your changes afterwards.
Great to hear about Neutronian's interest; I'd be interested in feedback after the due diligence.
Thanks!

**Comment by psa-neutronian** [comment]
Changes pushed.

As mentioned earlier, I'm working on more changes for the external modules and I'll open another ticket for those.

**Comment by jnioche** [comment]
Looks good, thanks Paul
