### ISSUE TITLE
URLFilters show logging as if ParseFilters

### ISSUE THREAD

**Issue by GerbenKD** [DigitalPebble/storm-crawler#886]
I'm not sure whether the following line is intentional. 

https://github.com/DigitalPebble/storm-crawler/blob/eb735b4f704e86ccdf004ca4dee107f331fad2a4/core/src/main/java/com/digitalpebble/stormcrawler/util/Configurable.java#L33

When debugging my URLFilters it was confusing that they were logging as ParseFilters because of the line above.

cheers,

Gerben

**Comment by jnioche** [comment]
Good catch. Overlooked that when I refactored the code. Not sure if there is a way of getting the actual class implementing the interface. Alternatively could rewrite into 
_LoggerFactory.getLogger(Configurable.class);_

**Comment by GerbenKD** [comment]
I've never seen that with the actual implementing class. For me it would make most sense to log from Configurable.class. 

Gerben
