### ISSUE TITLE
[Elasticsearch] Fielddata is disabled on text fields by default.

### ISSUE THREAD

**Issue by fackse** [DigitalPebble/storm-crawler#929]
In version 2.1 there seems to be a bug in the ES_IndexInit.sh. Unfortunately I'm not quite fit about Elasticsearch, however the AggregationSpout gives an error message:

> 2021-11-19 10:57:50.715 c.d.s.e.p.AggregationSpout I/O dispatcher 5 [ERROR]  Exception with ES query
> org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
>         at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[stormjar.jar:?]
>         at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1793) ~[stormjar.jar:?]
>         at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1770) ~[stormjar.jar:?]
>         at org.elasticsearch.client.RestHighLevelClient$1.onFailure(RestHighLevelClient.java:1686) [stormjar.jar:?]
>         at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:598) [stormjar.jar:?]
>         at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343) [stormjar.jar:?]
>         at org.elasticsearch.client.RestClient$1.completed(RestClient.java:327) [stormjar.jar:?]
>         at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122) [stormjar.jar:?]
>         at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181) [stormjar.jar:?]
>         at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448) [stormjar.jar:?]
>         at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338) [stormjar.jar:?]
>         at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) [stormjar.jar:?]
>         at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) [stormjar.jar:?]
>         at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) [stormjar.jar:?]
>         at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) [stormjar.jar:?]
>         at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) [stormjar.jar:?]
>         at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) [stormjar.jar:?]
>         at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) [stormjar.jar:?]
>         at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) [stormjar.jar:?]
>         at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) [stormjar.jar:?]
>         at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) [stormjar.jar:?]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
>         Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://elasticsearch:9200], URI [/status/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true], status line [HTTP/1.1 400 Bad Request]
> {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [key] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"status","node":"7x7XAkS4S7m2Xbtz2E-BXQ","reason":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [key] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [key] in order to load field data by uninverting the inverted index. Note that this can use significant memory.","caused_by":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [key] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}}},"status":400}
>                 at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:283) ~[stormjar.jar:?]
>                 at org.elasticsearch.client.RestClient.access$1700(RestClient.java:97) ~[stormjar.jar:?]
>                 at org.elasticsearch.client.RestClient$1.completed(RestClient.java:331) [stormjar.jar:?]
>                 at org.elasticsearch.client.RestClient$1.completed(RestClient.java:327) [stormjar.jar:?]
>                 at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122) [stormjar.jar:?]
>                 at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181) [stormjar.jar:?]
>                 at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448) [stormjar.jar:?]
>                 at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338) [stormjar.jar:?]
>                 at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) [stormjar.jar:?]
>                 at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) [stormjar.jar:?]
>                 at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) [stormjar.jar:?]
>                 at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) [stormjar.jar:?]
>                 at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) [stormjar.jar:?]
>                 at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) [stormjar.jar:?]
>                 at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) [stormjar.jar:?]
>                 at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) [stormjar.jar:?]
>                 at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) [stormjar.jar:?]
>                 at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) [stormjar.jar:?]
>                 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
> Caused by: org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=illegal_argument_exception, reason=Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [key] in order to load field data by uninverting the inverted index. Note that this can use significant memory.]
>         at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:496) ~[stormjar.jar:?]
>         at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:407) ~[stormjar.jar:?]
>         at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:437) ~[stormjar.jar:?]
>         at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:603) ~[stormjar.jar:?]
>         at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:169) ~[stormjar.jar:?]
>         ... 21 more
> Caused by: org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=illegal_argument_exception, reason=Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [key] in order to load field data by uninverting the inverted index. Note that this can use significant memory.]
>         at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:496) ~[stormjar.jar:?]
>         at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:407) ~[stormjar.jar:?]
>         at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:437) ~[stormjar.jar:?]
>         at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:407) ~[stormjar.jar:?]
>         at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:437) ~[stormjar.jar:?]
>         at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:603) ~[stormjar.jar:?]
>         at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:169) ~[stormjar.jar:?]
>         ... 21 more

However, in the DevOps console of Kibana the query works. Currently I have worked around the problem by creating the status index as follows:
```
PUT status
{
	"settings": {
		"index": {
			"number_of_shards": 10,
			"number_of_replicas": 1,
			"refresh_interval": "5s"
		}
	},
	"mappings": {
			"dynamic_templates": [{
				"metadata": {
					"path_match": "metadata.*",
					"match_mapping_type": "string",
					"mapping": {
						"type": "keyword",
						"fielddata": true
					}
				}
			}],
			"_source": {
				"enabled": true
			},
			"properties": {
				"key": {
					"type": "keyword",
					"index": true
					
				},
				"nextFetchDate": {
					"type": "date",
					"format": "date_optional_time"
				},
				"status": {
					"type": "keyword"
				},
				"url": {
					"type": "keyword"
				}
			}
	}
}

```
A warning is showed:

> #! dynamic template [metadata] has invalid content [{"path_match":"metadata.*","match_mapping_type":"string","mapping":{"fielddata":true,"type":"keyword"}}], attempted to validate it with the following match_mapping_type: [string], caused by [unknown parameter [fielddata] on mapper [__dynamic__metadata] of type [keyword]]
> {
>   "acknowledged" : true,
>   "shards_acknowledged" : true,
>   "index" : "status"
> }
> 

but it works anyway.
PS: Unfortunately I can not set labels

**Comment by jnioche** [comment]
thanks @fackse I will try to reproduce the problem
which version of ES are you on?
_key_ is [already marked as a keyword](https://github.com/DigitalPebble/storm-crawler/blob/master/external/elasticsearch/archetype/src/main/resources/archetype-resources/ES_IndexInit.sh#L37) so I am not sure why you are getting this

re:labels - I think only admins can set them for some reason

**Comment by fackse** [comment]
Hi @jnioche,
I'm using 7.14.2. Sorry, but I'm not an expert and so I just "hacked around" until it worked.

**Comment by jnioche** [comment]
> I'm using 7.14.2. Sorry, but I'm not an expert and so I just "hacked around" until it worked.
Don't apologise! Hacking around is what I do for a living ;-)

I have tried with 7.15.2 with a topology generated from the 2.2-SNAPSHOT archetype and did not get the error. Same with the 2.1 archetype.

Where did you get the _ES_indexInit.sh_ file from? It could be that it dates from a while back before _key_ was used as the default field name.

**Comment by fackse** [comment]
Thanks for the kind reply :-)
I got the ES_indexInit.sh from the generated archetype (2.1). But then I assume that the error comes from somewhere else. I run the whole thing as a Docker Swarm, possibly the cause is in the Elasticsearch image. Anyway, if the error occurs again, I'll take a closer look.
