### ISSUE TITLE
Track target of redirection

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#96]
We should store the target of a redirection in the metadata of the redirected URL, regardless of whether the target gets filtered or not.  This will make it easier to debug the behaviour of the Fetcher

**Comment by w0mbat** [comment]
Yes this sounds good to me - we could need this in our analysis platform. How would you like to store this information in the metadata?

**Comment by jnioche** [comment]
Implemented. Using the key `_redirTo` to track the value of the redirection.
