### ISSUE TITLE
JSoupParserBolt - toOutlinks method as protected

### ISSUE THREAD

**Issue by juli-alvarez** [DigitalPebble/storm-crawler#963]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the best place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use StackOverflow
       instead with the label 'stormcrawler': https://stackoverflow.com/questions/tagged/stormcrawler 

 - [ ] Bug report. If you’ve found a bug, please include a test if you can, it makes it a lot easier to fix things. Use the label 'bug' on the issue.
 
 - [X] Feature request. Please use the label 'wish' on the issue.

Thanks!

Hi @jnioche!
Is it possible to make toOutlinks method in JSoupParserBolt protected? We're allowing to customize the number of outlinks processed using a max in the metadata and we'd need to override that method in order to create create a new map with this limit and pass it to the parent's toOutlinks.
Thanks!

**Comment by jnioche** [comment]
sure, done!
