### ISSUE TITLE
FetcherBolt - customize fetcher delay based on metadata property

### ISSUE THREAD

**Issue by juli-alvarez** [DigitalPebble/storm-crawler#964]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the best place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use StackOverflow
       instead with the label 'stormcrawler': https://stackoverflow.com/questions/tagged/stormcrawler 

 - [ ] Bug report. If you’ve found a bug, please include a test if you can, it makes it a lot easier to fix things. Use the label 'bug' on the issue.
 
 - [X] Feature request. Please use the label 'wish' on the issue.

Thanks!

Hi @jnioche!
We're trying to customize the crawl delay based on a property that comes in the metadata. We're passing this value to the fetchQueues.getFetchItemQueue() and using it to create the new FetchItemQueue. In case that the item already exists we set the minCrawlDelay if the new fetcher delay is greater than the current one (we take the less aggressive).
What do you think? It's possible to get this changes into the core?
Thanks!

**Comment by jnioche** [comment]
why not? do you want to submit a PR for it?

**Comment by juli-alvarez** [comment]
Done! https://github.com/DigitalPebble/storm-crawler/pull/967
