### ISSUE TITLE
Update jsoup from 1.14.3 to 1.15.1

### ISSUE THREAD

**Issue by rzo1** [DigitalPebble/storm-crawler#968]
Bumps [jsoup](https://github.com/jhy/jsoup) from 1.14.3 to 1.15.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/jhy/jsoup/releases">jsoup's releases</a>.</em></p>
<blockquote>
<p>jsoup 1.15.1 is out now with a bunch of <a href="https://jsoup.org/news/release-1.15.1">improvements and bug fixes</a>.</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/jhy/jsoup/blob/master/CHANGES">jsoup's changelog</a>.</em></p>
<blockquote>
<p>jsoup changelog</p>
<p>*** Release 1.15.1 [2022-May-15]</p>
<ul>
<li>
<p>Change: removed previously deprecated methods and classes (including org.jsoup.safety.Whitelist; use
org.jsoup.safety.Safelist instead).</p>
</li>
<li>
<p>Improvement: when converting jsoup Documents to W3C Documents in W3CDom, preserve HTML valid attribute names if the
input document is using the HTML syntax. (Previously, would always coerce using the more restrictive XML syntax.)
<a href="https://github.com/jhy/jsoup/pull/1648">jhy/jsoup#1648</a></p>
</li>
<li>
<p>Improvement: added the :containsWholeText(text) selector, to match against non-normalized Element text. That can be
useful when elements can only be distinguished by e.g. specific case, or leading whitespace, etc.
<a href="https://github.com/jhy/jsoup/issues/1636">jhy/jsoup#1636</a></p>
</li>
<li>
<p>Improvement: added Element#wholeOwnText() to retrieve the original (non-normalized) ownText of an Element. Also
added the :containsWholeOwnText(text) selector, to match against that. BR elements are now treated as newlines
in the wholeText methods.
<a href="https://github.com/jhy/jsoup/issues/1636">jhy/jsoup#1636</a></p>
</li>
<li>
<p>Improvement: added the :matchesWholeText(regex) and :matchesWholeOwnText(regex) selectors, to match against whole
(non-normalized, case sensitive) element text and own text, respectively.
<a href="https://github.com/jhy/jsoup/issues/1636">jhy/jsoup#1636</a></p>
</li>
<li>
<p>Improvement: when evaluating an XPath query against a context element, the complete document is now visible to the
query, vs only the context element's sub-tree. This enables support for queries outside (parent or sibling) the
element, e.g. ancestor-or-self::*.
<a href="https://github.com/jhy/jsoup/issues/1652">jhy/jsoup#1652</a></p>
</li>
<li>
<p>Improvement: allow a maxPaddingWidth on the indent level in OutputSettings when pretty printing. This defaults to
30 to limit the indent level for very deeply nested elements, and may be disabled by setting to -1.
<a href="https://github.com/jhy/jsoup/pull/1655">jhy/jsoup#1655</a></p>
</li>
<li>
<p>Improvement: when cloning a Node or an Element, the clone gets a cloned OwnerDocument containing only that clone, so
as to preserve applicable settings, such as the Pretty Print settings.
<a href="https://github.com/jhy/jsoup/issues/763">jhy/jsoup#763</a></p>
</li>
<li>
<p>Improvement: added a convenience method Jsoup.parse(File).
<a href="https://github.com/jhy/jsoup/issues/1693">jhy/jsoup#1693</a></p>
</li>
<li>
<p>Improvement: in the NodeTraversor, added default implementations for NodeVisitor.tail() and NodeFilter.tail(), so
that code using only head() methods can be written as lambdas.</p>
</li>
<li>
<p>Improvement: in NodeTraversor, added support for removing nodes via Node.remove() during NodeVisitor.head().
<a href="https://github.com/jhy/jsoup/issues/1699">jhy/jsoup#1699</a></p>
</li>
<li>
<p>Improvement: added Node.forEachNode(Consumer) and Element.forEach(Consumer&lt;Element) methods, to efficiently
traverse the DOM with a functional interface.
<a href="https://github.com/jhy/jsoup/issues/1700">jhy/jsoup#1700</a></p>
</li>
<li>
<p>Bugfix: boolean attribute names should be case-insensitive, but were not when the parser was configured to preserve</p>
</li>
</ul>

</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/jhy/jsoup/commit/3ffbeebc0959e2ada7ed1b4595338d2f09597e85"><code>3ffbeeb</code></a> [maven-release-plugin] prepare release jsoup-1.15.1</li>
<li><a href="https://github.com/jhy/jsoup/commit/2b4a1dacf69b0e0fde3baeebbcf7ce1228da0342"><code>2b4a1da</code></a> Changelog for <a href="https://github.com/jhy/jsoup/issues/1763">#1763</a></li>
<li><a href="https://github.com/jhy/jsoup/commit/eaf5028718840d71c9a7f94f538b65b135012702"><code>eaf5028</code></a> Fix/safelist deep copy constructor (<a href="https://github.com/jhy/jsoup/issues/1763">#1763</a>)</li>
<li><a href="https://github.com/jhy/jsoup/commit/72612480cfc5a8b3c6ca31097cfd908121a638da"><code>7261248</code></a> Bump maven-bundle-plugin from 5.1.5 to 5.1.6 (<a href="https://github.com/jhy/jsoup/issues/1768">#1768</a>)</li>
<li><a href="https://github.com/jhy/jsoup/commit/c76cad626cdd34aaa700336f1adbb28d36e90032"><code>c76cad6</code></a> Bump gson from 2.8.9 to 2.9.0 (<a href="https://github.com/jhy/jsoup/issues/1769">#1769</a>)</li>
<li><a href="https://github.com/jhy/jsoup/commit/3cc012dbaa0c5af34f41ece6aed1ff622a03e65d"><code>3cc012d</code></a> Bump maven-surefire-plugin from 3.0.0-M5 to 3.0.0-M6 (<a href="https://github.com/jhy/jsoup/issues/1770">#1770</a>)</li>
<li><a href="https://github.com/jhy/jsoup/commit/f881e81d83cc413fa90a1af6579072a316df6784"><code>f881e81</code></a> Bump maven-failsafe-plugin from 3.0.0-M5 to 3.0.0-M6 (<a href="https://github.com/jhy/jsoup/issues/1771">#1771</a>)</li>
<li><a href="https://github.com/jhy/jsoup/commit/e6dc745d209391ae4cec8371b9b189b36f4b8987"><code>e6dc745</code></a> Bump maven-javadoc-plugin from 3.3.1 to 3.4.0 (<a href="https://github.com/jhy/jsoup/issues/1772">#1772</a>)</li>
<li><a href="https://github.com/jhy/jsoup/commit/768b6cf31d2f7bb931312f9588c440bcd946eb15"><code>768b6cf</code></a> Bump maven-compiler-plugin from 3.8.1 to 3.10.1 (<a href="https://github.com/jhy/jsoup/issues/1732">#1732</a>)</li>
<li><a href="https://github.com/jhy/jsoup/commit/cb9fea2a83f131dbfb1cef3f9433596b358888cb"><code>cb9fea2</code></a> Bump japicmp-maven-plugin from 0.15.4 to 0.15.7 (<a href="https://github.com/jhy/jsoup/issues/1729">#1729</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/jhy/jsoup/compare/jsoup-1.14.3...jsoup-1.15.1">compare view</a></li>
</ul>
</details>
<br />

---

<details>
<summary>Dependabot commands</summary>
<br />
You can trigger Dependabot actions by commenting on this MR

- `$dependabot rebase` will rebase this MR
- `$dependabot recreate` will recreate this MR rewriting all the manual changes and resolving conflicts

</details>

**Comment by jnioche** [comment]
thanks @rzo1 
did you check that it doesn't break the [Xsoup](https://github.com/code4craft/xsoup) based resources in https://github.com/DigitalPebble/storm-crawler/tree/master/core/src/main/java/com/digitalpebble/stormcrawler/jsoup still work after the update?

**Comment by rzo1** [comment]
@jnioche I did run `JSoupFiltersTest` after the upgrade, which didn't break. In addition, I conducted an upgrade of JSoup in [Xsoup](https://github.com/code4craft/xsoup/pull/54) locally and did run their unit tests, which didn't break either. It seems, they did not depend on any removed classes / methods (no compile or runtime issues on the Xsoup site).

 Therefore, I am confident, that it does not break anything but might enable new XPath-based use-cases :)

**Comment by rzo1** [comment]
We might want to add an `exclusion` block for `jsoup` in the `xsoup` declaration to avoid pulling `1.13.x` (which is contained in the latest released Xsoup version) and omit the conflict warning with 1.14.3 or (now) 1.15.1). Wdyt?

**Comment by jnioche** [comment]
> We might want to add an `exclusion` block for `jsoup` in the `xsoup` declaration to avoid pulling `1.13.x` (which is contained in the latest released Xsoup version) and omit the conflict warning with 1.14.3 or (now) 1.15.1).
> 
> Wdyt?

Excellent idea!

**Comment by rzo1** [comment]
Ok - will add the exclusion later.
