### ISSUE TITLE
Fix starvation and busy waiting of ES StatusUpdaterBolt 

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#986]
See related discussion in #983

**Comment by FelixEngl** [comment]
Fixed it: 
- `StatusUpdaterBold`: https://github.com/DigitalPebble/storm-crawler/pull/988
- `IndexerBold` https://github.com/DigitalPebble/storm-crawler/pull/989

**Comment by jnioche** [comment]
Thanks @FelixEngl
