### ISSUE TITLE
JSON stringifying metadata keys

### ISSUE THREAD

**Issue by jakekdodd** [DigitalPebble/storm-crawler#99]
Was adding support for ETags in HttpResponse when I realized that, when using If-Modified-Since, it's looking for a metadata key actually named 'If-Modified-Since.' I think I originally did this for consistency, but now it seems like a bad idea. First because we're normalizing HTTP headers (so 'if-modified-since' would be better). But more importantly, I think these behavior-changing metadata keys should be JSON compatible. A common use case will be to deserialize known metadata within or directly downstream from the spout, and JSON-compliant key names will be required for many spout types. So, 'ifModifiedSince,' and the ETag key would be 'ifNoneMatch.' 

It's a super simple fix, but because it's changing the contract, I wanted to run it by you guys first.

**Comment by GuiForget** [comment]
No using the same key as the HTTP Header makes more sense to me. To me the key names should reflect what the data is, maybe something like "cachedEtag" and "cachedTimestamp".

**Comment by jakekdodd** [comment]
That's the idea with ifModifiedSince and ifNoneMatch, but they're using the request header names. Using the response names would be totally OK, too. In that case, cachedEtag and cachedLastModified

**Comment by jakekdodd** [comment]
Now that I think about it, I like using the response field names more because they do describe the data better, from a user's perspective.

**Comment by jakekdodd** [comment]
Committed in 2c207eefd0522146de5e345ad45edfa11bc02596, need to modify the wiki now

**Comment by jakekdodd** [comment]
Wiki has been updated
