### ISSUE TITLE
storm ui

### ISSUE THREAD

**Issue by abls1** [DigitalPebble/storm-crawler#995]
What kind of issue is this?

 WARNING: The path /ui could not be found. Will not import it. Welcome to the Storm compiler! Root directory: /usr/lib/storm Compiler boot in 51.74 ms Type 'licenses' to show licenses for all currently used module

Thanks!

**Comment by rzo1** [comment]
I don't understand your question / report. Please add some more details (versions, os, etc.).

**Comment by jnioche** [comment]
Closing. Not enough information and the question is about Apache Storm in general, not SC specifically
